# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(max_length=255, unique=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'patch_log',
            },
        ),
    ]
