
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b30d396fa81a2130509dd769a93f3c3182a6a842",
 "version": "1.2.36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
