
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.19'
version_full = '2bad8b6bfceaf91b9ea7e87f0bfa64699c7b7828'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

