
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9f8bca9a2f5159e4649c05f1aa1eb018c83af38b",
 "version": "2.10.114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
