site_name: ObjDiff Documentation
site_description: Objdiff, an easy way to get the differences between 2 trees of objects
site_author: Da_Blitz
repo_url: http://blitz.works/objdiff/
repo_name: ObjDiff src
theme: cyborg
pages:
 - index.md
 - Usage:
   - Installation.md
   - Examples.md
   - API.md
   - Limitations.md
 - Extras:
   - CLI.md
   - Tips_and_tricks.md
   - Background.md
 - Changelog.rst
copyright: 'Copyright: Da_Blitz (2016)'
