
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.0'
version_full = '9ff6e76548277d25a31f861331044d4900f4c7dc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

