
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "af7dc1616debf7cd9dd8d559f409fc4b3db51205",
 "version": "v0.0.0.post104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
