# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import os

class Migration(migrations.Migration):

    replaces = [('django_speach_synthesizer', '0001_initial'), ('django_speach_synthesizer', '0002_soundfile_user')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=os.path.join(settings.BASE_DIR, 'generated'))),
                ('text', models.TextField()),
                ('command', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('wav', 'wav')], max_length=5)),
                ('dc', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
