__version__ = "0.6.0"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = '(detached from v0.6.0)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '993705e97b8ddeed67c3fa0fc5189e58ab23bc3e'
__git_head_subject__ = 'Finished Release v0.6.0'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-07-11 13:05:25'
