
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "21801f9bbbb9518fc48dfd70a5fdc1a4df485d56",
 "version": "0.post.dev261"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
