
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4'
version_full = 'cdbd1637caf7d0c290253c233cb6172b4f56d454'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

