
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "60fb78bf7153aab1d0f391d2ece7a4380b3e6ed7",
 "version": "1.0.0.post.dev107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
