
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.4'
version_full = 'b2ea0f39ecce39738410a9cc7b3ad7f3e6d73284'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

