---
#default variables used for setting up myria-web
#hadoop_binaries_url: http://apache.osuosl.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz
hadoop_binaries_url: "http://s3-us-west-2.amazonaws.com/uwdb/myria/deploy-cache/hadoop/hadoop-{{ hadoop_version }}.tar.gz"
hadoop_download_path: /tmp/hadoop-{{ hadoop_version }}.tar.gz
hadoop_install_path: "{{ install_base_path }}/hadoop-{{ hadoop_version }}"
yarn_nm_dir: '{{data_vol_mount_dir}}/nm-local'
hdfs_namenode_data_dir: '{{data_vol_mount_dir}}/namenode'
hdfs_datanode_data_dir: '{{data_vol_mount_dir}}/datanode'
hdfs_replication_factor: 2
node_mem_gb: "{{ NODE_MEM_GB | float }}"
node_vcores: "{{ NODE_VCORES | int }}"
hadoop_log_dir: "{{ data_vol_mount_dir }}/hadoop/logs"
