
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6ec38f7fcc1f31cfb73001fb26ea3c71c2e0d0e2",
 "version": "1.0.0.post.dev115"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
