
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6b70461e3a0e123faccabf8a2ad625ada3589aa6",
 "version": "2.10.107"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
