
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cb05840174d58a13afd970ee42c23259b1d9897d",
 "version": "1.0.0a15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
