
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "303ad69c838d4e5114b474f03349da5c59011f36",
 "version": "1.0.0.post.dev204"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
