
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "be2f9056866313083839920f7e3fc8c210b8c63e",
 "version": "1.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
