
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "674a68b61daa8d2ef12e8ecdb0c73b4fec90ee9e",
 "version": "0.1.post21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
