
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1f65dae16f26af85b556d5532a944fe2b991aa89",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
