
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.7.2',
    'branch_nick': '(no',
    'revision_id': 'c8309471124eaed5646b4c1b3d3617c3dee47b84',
    'revno': 4352
}
