
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.6.8',
    'branch_nick': '(no',
    'revision_id': 'f55b685266095c6c66833bff8ebbe3b917ecee18',
    'revno': 4153
}
