# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20151216_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default Bundle'),
        ),
    ]
