# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_bundle_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4000, null=True, verbose_name='Notes'),
        ),
    ]
