
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.4'
version_full = '802c89ec0b7ac230776ca0f8c55e54806c26b717'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

