# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('destination_ip', models.GenericIPAddressField(verbose_name='Destination IP')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('protocol', models.CharField(default=b'', max_length=50, verbose_name='protocol')),
                ('ip_version', models.CharField(default=b'', max_length=50, verbose_name='IP Version')),
                ('desc', models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name='Description')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
