# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='ip_version',
            field=models.CharField(default='', max_length=50, verbose_name='IP Version'),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='protocol',
            field=models.CharField(default='', max_length=50, verbose_name='protocol'),
        ),
    ]
