# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_auto_20160523_1653'),
        ('alerts', '0002_auto_20160526_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='BLANK TITLE', max_length=50, verbose_name='protocol')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description')),
                ('delete_reason', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Delete reason')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='Destination IP')),
                ('port', models.PositiveIntegerField(verbose_name='Port')),
                ('protocol', models.CharField(default='', max_length=50, verbose_name='protocol')),
                ('ip_version', models.CharField(default='', max_length=50, verbose_name='IP Version')),
                ('soft_delete', models.BooleanField(default=False, verbose_name='Soft Delete')),
            ],
            options={
                'db_table': 'summaries',
            },
        ),
        migrations.AddField(
            model_name='alerts',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node', to='node.Node'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='summary', to='alerts.Summaries'),
        ),
    ]
