# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20160616_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node', to='node.Node'),
        ),
    ]
