# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20160616_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summaries',
            new_name='AlertSummaries',
        ),
        migrations.AlterField(
            model_name='alerts',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alert_summaries', to='alerts.AlertSummaries'),
        ),
        migrations.AlterModelTable(
            name='alertsummaries',
            table='alert_summaries',
        ),
    ]
