# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20160616_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='desc',
            new_name='descr',
        ),
    ]
