# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20160617_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=15, verbose_name='Alert Level'),
        ),
        migrations.AddField(
            model_name='alerts',
            name='time_stamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
