# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20160617_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Event Time Stamp')),
                ('iface_in', models.CharField(max_length=50, null=True, verbose_name='Interface In')),
                ('iface_out', models.CharField(max_length=50, null=True, verbose_name='Interface Out')),
                ('src_addr', models.GenericIPAddressField(null=True, verbose_name='Source Address')),
                ('dest_addr', models.GenericIPAddressField(null=True, verbose_name='Destination Address')),
                ('length', models.IntegerField(null=True, verbose_name='Length')),
                ('tos', models.CharField(max_length=10, null=True, verbose_name='Type Of Service')),
                ('prec', models.CharField(max_length=10, null=True, verbose_name='Precedence')),
                ('ttl', models.IntegerField(null=True, verbose_name='Time To Live')),
                ('packet_id', models.IntegerField(null=True, verbose_name='Packet ID')),
                ('frag_flags', models.CharField(max_length=50, null=True, verbose_name='Fragment Flags')),
                ('protocol', models.CharField(max_length=10, null=True, verbose_name='Packet Protocol')),
                ('src_port', models.IntegerField(null=True, verbose_name='Source Port')),
                ('dest_port', models.IntegerField(null=True, verbose_name='Destination Port')),
                ('window', models.IntegerField(null=True, verbose_name='Length of TCP Window')),
                ('reserved', models.CharField(max_length=10, null=True, verbose_name='Reserved Bits')),
                ('urgp', models.IntegerField(null=True, verbose_name='Urgent Pointer')),
                ('tcp_flags', models.CharField(max_length=50, null=True, verbose_name='TCP Flags')),
                ('udp_length', models.IntegerField(default=0, verbose_name='UDP Packet Length')),
                ('icmp_type', models.IntegerField(default=0, verbose_name='ICMP Type')),
                ('icmp_code', models.IntegerField(default=0, verbose_name='ICMP Code')),
                ('icmp_id', models.IntegerField(default=0, verbose_name='ICMP ID')),
                ('icmp_seq', models.IntegerField(default=0, verbose_name='ICMP Sequence')),
                ('icmp_error_header', models.BooleanField(default=False, verbose_name='Additional Event Information')),
                ('leftover', models.CharField(max_length=500, null=True, verbose_name='Unprocessed Event Data')),
                ('parent_id', models.IntegerField(null=True, verbose_name='Parent Event ID')),
            ],
            options={
                'db_table': 'alert_event',
            },
        ),
    ]
