# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alertevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertevent',
            old_name='timestamp',
            new_name='event_dt',
        ),
    ]
