# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20160622_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='event',
            field=models.CharField(max_length=1000, null=True, verbose_name='Raw Event Data'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='event_flag',
            field=models.CharField(max_length=30, null=True, verbose_name='Event Logging Flag'),
        ),
        migrations.RemoveField(
            model_name='alertevent',
            name='icmp_error_header',
        ),
        migrations.AlterModelTable(
            name='alertevent',
            table='iptables_alert_event',
        ),
    ]
