# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_auto_20160628_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertEvent',
            new_name='IPAlertEvent',
        ),
    ]
