# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_auto_20160628_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipalertevent',
            name='tz_offset',
            field=models.CharField(max_length=10, null=True, verbose_name='Time Zone Offset from GMT'),
        ),
    ]
