# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_auto_20160523_1653'),
        ('alerts', '0012_ipalertevent_tz_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='icmp_type',
            field=models.IntegerField(default=0, verbose_name='ICMP Type'),
        ),
        migrations.AddField(
            model_name='ipalertevent',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ae_node', to='node.Node'),
        ),
        migrations.AlterField(
            model_name='ipalertevent',
            name='tz_offset',
            field=models.CharField(max_length=10, null=True, verbose_name='Time Zone Offset from UTC'),
        ),
    ]
