# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_auto_20160722_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
