
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a9c92b226dac8811a3ecada57de3148a88a8aaf3",
 "version": "1.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
