
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a60a3087f448577d8492141388750dd3477c20a6",
 "version": "1.2.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
