
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d354fb0c08be229ce84bdb3eecbf2c10b0483303",
 "version": "1.2.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
