
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1b0d45d7387a2bacd56adfbb0ed04cd6b9296b67",
 "version": "1.0.0a13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
