
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.1'
version_full = '388f9e69a401a4b2601e24604cfa0ddabdf964ed'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

