heat_template_version: 2016-04-08

description: >
  Ceph Monitor service.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CephIPv6:
    default: False
    type: boolean
  CephMonKey:
    default: ''
    description: The Ceph monitors key. Can be created with ceph-authtool --gen-print-key.
    type: string
    hidden: true
  CinderRbdPoolName:
    default: volumes
    type: string
  CinderBackupRbdPoolName:
    default: backups
    type: string
  GlanceRbdPoolName:
    default: images
    type: string
  GnocchiRbdPoolName:
    default: metrics
    type: string
  NovaRbdPoolName:
    default: vms
    type: string

resources:
  CephBase:
    type: ./ceph-base.yaml

outputs:
  role_data:
    description: Role data for the Ceph Monitor service.
    value:
      config_settings:
        map_merge:
          - get_attr: [CephBase, role_data, config_settings]
          - ceph::profile::params::ms_bind_ipv6: {get_param: CephIPv6}
            ceph::profile::params::mon_key: {get_param: CephMonKey}
            tripleo::profile::base::ceph::mon::ceph_pools:
              - {get_param: CinderRbdPoolName}
              - {get_param: CinderBackupRbdPoolName}
              - {get_param: NovaRbdPoolName}
              - {get_param: GlanceRbdPoolName}
              - {get_param: GnocchiRbdPoolName}
      step_config: |
        include ::tripleo::profile::base::ceph::mon
