heat_template_version: 2016-04-08

description: >
  Ceph OSD service.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  CephBase:
    type: ./ceph-base.yaml

outputs:
  role_data:
    description: Role data for the Cinder OSD service.
    value:
      config_settings:
        get_attr: [CephBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::ceph::osd
