heat_template_version: 2016-04-08

description: >
  OpenStack Cinder Scheduler service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  CinderBase:
    type: ./cinder-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Cinder Scheduler role.
    value:
      config_settings:
        get_attr: [CinderBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::cinder::scheduler
