heat_template_version: 2016-04-08

description: >
  OpenStack Glance Registry service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  GlancePassword:
    description: The password for the glance service and db account, used by the glance services.
    type: string
    hidden: true
  GlanceWorkers:
    default: 0
    description: Number of workers for Glance service.
    type: number

outputs:
  role_data:
    description: Role data for the Glance Registry role.
    value:
      config_settings:
        glance::registry::database_connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://glance:'
              - {get_param: GlancePassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/glance'
        glance::registry::keystone_password: {get_param: GlancePassword}
        glance::registry::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri] }
        glance::registry::identity_uri: { get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix] }
        glance::registry::debug: {get_param: Debug}
        glance::registry::workers: {get_param: GlanceWorkers}
      step_config: |
        include ::tripleo::profile::base::glance::registry
