heat_template_version: 2016-04-08

description: >
  HAproxy service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Role data for the HAproxy role.
    value:
      step_config: |
        include ::tripleo::profile::base::haproxy
