heat_template_version: 2016-04-08

description: >
  Openstack Heat CloudWatch API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HeatWorkers:
    default: 0
    description: Number of workers for Heat service.
    type: number

resources:
  HeatBase:
    type: ./heat-base.yaml

outputs:
  role_data:
    description: Role data for the Heat Cloudwatch API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [HeatBase, role_data, config_settings]
          - heat::api_cloudwatch::workers: {get_param: HeatWorkers}
      step_config: |
        include ::tripleo::profile::base::heat::api_cloudwatch
