heat_template_version: 2016-04-08

description: >
  Openstack Heat base service. Shared for all Heat services.

parameters:
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number

outputs:
  role_data:
    description: Shared role data for the Heat services.
    value:
      config_settings:
        heat::rabbit_userid: {get_param: RabbitUserName}
        heat::rabbit_password: {get_param: RabbitPassword}
        heat::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        heat::rabbit_port: {get_param: RabbitClientPort}
        heat::debug: {get_param: Debug}
        heat::enable_proxy_headers_parsing: true
        # We need this because the default heat policy.json no longer works on TripleO
        # https://git.openstack.org/cgit/openstack/heat/commit/?id=ac86702172ddf01f5bdc3f3cd99d2e32ad9b7024
        heat::policy::policies:
          context_is_admin:
            key: 'context_is_admin'
            value: 'role:admin'
