heat_template_version: 2016-04-08

description: >
  Openstack Heat API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  HeatWorkers:
    default: 0
    description: Number of workers for Heat service.
    type: number
  HeatPassword:
    description: The password for the Heat service and db account, used by the Heat services.
    type: string
    hidden: true
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint

resources:
  HeatBase:
    type: ./heat-base.yaml

outputs:
  role_data:
    description: Role data for the Heat API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [HeatBase, role_data, config_settings]
          - heat::api::workers: {get_param: HeatWorkers}
            heat::keystone::auth::public_url: {get_param: [EndpointMap, HeatPublic, uri]}
            heat::keystone::auth::internal_url: {get_param: [EndpointMap, HeatInternal, uri]}
            heat::keystone::auth::admin_url: {get_param: [EndpointMap, HeatAdmin, uri]}
            heat::keystone::auth::password: {get_param: HeatPassword}
            heat::keystone::auth::region: {get_param: KeystoneRegion}
      step_config: |
        include ::tripleo::profile::base::heat::api
