heat_template_version: 2016-04-08

description: >
  OpenStack Neutron L3 agent configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    type: string
    default: ''
  NeutronExternalNetworkBridge:
    description: Name of bridge used for external network traffic.
    type: string
    default: 'br-ex'

resources:

  NeutronBase:
    type: ./neutron-base.yaml

outputs:
  role_data:
    description: Role data for the Neutron L3 agent service.
    value:
      config_settings:
        map_merge:
          - get_attr: [NeutronBase, role_data, config_settings]
          - neutron::agents::l3::external_network_bridge: {get_param: NeutronExternalNetworkBridge}
      step_config: |
        include tripleo::profile::base::neutron::l3
