heat_template_version: 2016-04-08

description: >
  OpenStack Nova base service. Shared for all Nova services.

parameters:
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  Debug:
    type: string
    default: ''
    description: Set to True to enable debugging on all services.

outputs:
  role_data:
    description: Role data for the Neutron base service.
    value:
      config_settings:
        nova::rabbit_password: {get_param: RabbitPassword}
        nova::rabbit_user: {get_param: RabbitUserName}
        nova::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        nova::rabbit_port: {get_param: RabbitClientPort}
        nova::debug: {get_param: Debug}
