heat_template_version: 2016-04-08

description: >
  OpenStack Nova Vncproxy service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  NovaBase:
    type: ./nova-base.yaml

outputs:
  role_data:
    description: Role data for the Nova Vncproxy service.
    value:
      config_settings:
        get_attr: [NovaBase, role_data, config_settings]
      step_config: |
        include tripleo::profile::base::nova::vncproxy
