heat_template_version: 2016-04-08

description: >
  OpenStack Nova Compute service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  NovaBase:
    type: ./nova-base.yaml

outputs:
  role_data:
    description: Role data for the Nova Compute service.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaBase, role_data, config_settings]
          - nova::compute::libvirt::manage_libvirt_services: false
          # we manage migration in nova common puppet profile
            nova::compute::libvirt::migration_support: false
            tripleo::profile::base::nova::manage_migration: true
            tripleo::profile::base::nova::nova_compute_enabled: true
      step_config: |
        # TODO(emilien): figure how to deal with libvirt profile.
        # We'll probably threat it like we do with Neutron plugins.
        # Until then, just include it in the default nova-compute role.
        include tripleo::profile::base::nova::compute::libvirt
