heat_template_version: 2016-04-08

description: >
  OpenStack Nova API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NovaWorkers:
    default: 0
    description: Number of workers for Nova API service.
    type: number

resources:
  NovaBase:
    type: ./nova-base.yaml

outputs:
  role_data:
    description: Role data for the Nova API service.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaBase, role_data, config_settings]
          - nova::api::osapi_compute_workers: {get_param: NovaWorkers}
          - nova::api::metadata_workers: {get_param: NovaWorkers}
      step_config: |
        include tripleo::profile::base::nova::api
