heat_template_version: 2016-04-08

description: >
  OpenStack Sahara API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  SaharaPassword:
    default: unset
    description: The password for the sahara service account, used by sahara-api.
    type: string
    hidden: true
  SaharaWorkers:
    default: 0
    description: The number of workers for the sahara-api.
    type: number
  SaharaApiVirtualIP:
    type: string
    default: ''
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint

resources:
  SaharaBase:
    type: ./sahara-base.yaml

outputs:
  role_data:
    description: Role data for the Sahara API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [SaharaBase, role_data, config_settings]
          - sahara::host: {get_param: SaharaApiVirtualIP}
            sahara::port: {get_param: [EndpointMap, SaharaInternal, port]}
            sahara::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri] }
            sahara::identity_uri: { get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix] }
            sahara::admin_password: {get_param: SaharaPassword}
            sahara::service::api::api_workers: {get_param: SaharaApiWorkers}
            sahara::keystone::auth::public_url: {get_param: [EndpointMap, SaharaPublic, uri]}
            sahara::keystone::auth::internal_url: {get_param: [EndpointMap, SaharaInternal, uri]}
            sahara::keystone::auth::admin_url: {get_param: [EndpointMap, SaharaAdmin, uri]}
            sahara::keystone::auth::password: {get_param: SaharaPassword }
            sahara::keystone::auth::region: {get_param: KeystoneRegion}
      step_config: |
        include ::tripleo::profile::base::sahara::api
