heat_template_version: 2016-04-08

description: >
  OpenStack Sahara base service. Shared for all Sahara services.

parameters:
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  Debug:
    type: string
    default: ''
    description: Set to True to enable debugging on all services.

outputs:
  role_data:
    description: Role data for the Sahara base service.
    value:
      config_settings:
        sahara::rabbit_password: {get_param: RabbitPassword}
        sahara::rabbit_user: {get_param: RabbitUserName}
        sahara::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
        sahara::rabbit_port: {get_param: RabbitClientPort}
        sahara::debug: {get_param: Debug}
        sahara::use_neutron: true
        sahara::plugins:
          - cdh
          - hdp
          - mapr
          - vanilla
          - spark
          - storm
        sahara::rpc_backend: rabbit
