heat_template_version: 2016-04-08

description: >
  SNMP client configured with Puppet, to facilitate Ceilometer Hardware
  monitoring in the undercloud. This service is required to enable hardware
  monitoring.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  SnmpdReadonlyUserName:
    default: ro_snmp_user
    description: The user name for SNMPd with readonly rights running on all Overcloud nodes
    type: string
  SnmpdReadonlyUserPassword:
    description: The user password for SNMPd with readonly rights running on all Overcloud nodes
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the SNMP services
    value:
      config_settings:
        snmpd_readonly_user_name: {get_param: SnmpdReadonlyUserName}
        snmpd_readonly_user_password: {get_param: SnmpdReadonlyUserPassword}
      step_config: |
        include ::tripleo::profile::base::snmp
