heat_template_version: 2016-04-08

description: >
  OpenStack Swift Proxy service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  SwiftPassword:
    description: The password for the swift service account, used by the swift proxy services.
    type: string
    hidden: true
  SwiftWorkers:
    default: 0
    description: Number of workers for Swift service.
    type: number
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint


outputs:
  role_data:
    description: Role data for the Swift proxy service.
    value:
      config_settings:
        # Swift
        swift::proxy::authtoken::auth_uri: {get_param: [EndpointMap, KeystoneInternal, uri]}
        swift::proxy::authtoken::identity_uri: {get_param: [EndpointMap, KeystoneAdmin, uri_no_suffix]}
        swift::proxy::authtoken::admin_password: {get_param: SwiftPassword}
        swift::proxy::workers: {get_param: SwiftWorkers}
        swift::keystone::auth::public_url: {get_param: [EndpointMap, SwiftPublic, uri]}
        swift::keystone::auth::internal_url: {get_param: [EndpointMap, SwiftInternal, uri]}
        swift::keystone::auth::admin_url: {get_param: [EndpointMap, SwiftAdmin, uri]}
        swift::keystone::auth::public_url_s3: {get_param: [EndpointMap, SwiftS3Public, uri]}
        swift::keystone::auth::internal_url_s3: {get_param: [EndpointMap, SwiftS3Internal, uri]}
        swift::keystone::auth::admin_url_s3: {get_param: [EndpointMap, SwiftS3Admin, uri]}
        swift::keystone::auth::password: {get_param: SwiftPassword}
        swift::keystone::auth::region: {get_param: KeystoneRegion}
      step_config: |
        include ::tripleo::profile::base::swift::proxy
