sudo: false

language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - make
      - gcc
      - qemu-utils
      - xorriso
      - zlib1g-dev

before_script:
  - export PATH=$PATH:$PWD/bin
  - export PREFIX=$PWD

install:
  - pip install tox
  - pip install coveralls

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

script: tox

after_success:
  - coveralls
