# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Aygit ad\u0131n\u0131 giriniz', max_length=30)),
                ('slug', models.SlugField(help_text='Url adresi (Otomatik olarak alinir)')),
                ('image', models.ImageField(default='images/image.png', upload_to='images/%Y/%m/%d')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
    ]
