
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9efdd5797ea735420899a1c0c7c9d91ff6b55a6a",
 "version": "0.4.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
