
/* #########################################################################
 * [2016-08-11 14:50:47.079000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___BASE_NODE_RPC___
#define ___BASE_NODE_RPC___

#include "BaseNodeRpc/Properties.h"
#include "BaseNodeRpc/CommandProcessor.h"

#endif  // #ifndef ___BASE_NODE_RPC___

