# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:36
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_auto_20151113_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='node',
            name='register_date',
        ),
        migrations.AddField(
            model_name='node',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='last_connection',
            field=models.DateField(auto_now_add=True, default=timezone.now(), verbose_name='Last Connection Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='registered',
            field=models.DateField(auto_now_add=True, default=timezone.now(), verbose_name='Registration Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodebundle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodebundle',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
