# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20151216_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInterfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='Interface Name')),
                ('uuid', models.CharField(max_length=64, null=True, verbose_name='Block ID')),
                ('type', models.CharField(max_length=256, verbose_name='Interface Type')),
                ('device', models.CharField(max_length=256, verbose_name='Device Name')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
            options={
                'db_table': 'node_interfaces',
            },
        ),
        migrations.RemoveField(
            model_name='node',
            name='registered',
        ),
        migrations.AlterField(
            model_name='node',
            name='system',
            field=models.CharField(max_length=50, verbose_name='Node System'),
        ),
        migrations.AddField(
            model_name='nodeinterfaces',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
        ),
    ]
