# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_auto_20151229_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_connection',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Connection Timestamp'),
        ),
        migrations.AlterField(
            model_name='node',
            name='python_version',
            field=models.CharField(max_length=255, verbose_name='Python Version'),
        ),
    ]
