# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_auto_20151229_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='python_version',
            field=models.CharField(max_length=256, verbose_name='Python Version'),
        ),
        migrations.AlterField(
            model_name='node',
            name='system',
            field=models.CharField(max_length=256, verbose_name='FQDN System Name'),
        ),
    ]
