# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20151229_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nodebundle',
            unique_together=set([('node', 'bundle')]),
        ),
    ]
