# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_auto_20151229_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='system',
        ),
        migrations.AddField(
            model_name='node',
            name='hostname',
            field=models.CharField(default='', max_length=256, verbose_name='Host name'),
        ),
        migrations.AddField(
            model_name='node',
            name='os',
            field=models.CharField(choices=[('linux', 'Linux')], default='', max_length=30, verbose_name='OS Name'),
        ),
    ]
