# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_auto_20160105_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodebundle',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='node.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='nodebundle',
            unique_together=set([]),
        ),
    ]
