# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_auto_20160111_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeinterfaces',
            old_name='type',
            new_name='interface_type',
        ),
        migrations.AddField(
            model_name='node',
            name='push',
            field=models.BooleanField(default=True, verbose_name='Push'),
        ),
        migrations.AddField(
            model_name='node',
            name='system',
            field=models.CharField(default='', max_length=256, verbose_name='System'),
        ),
    ]
