# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_auto_20160427_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_state',
            field=models.CharField(default='Off', max_length=100, verbose_name='Node State'),
        ),
        migrations.AddField(
            model_name='node',
            name='polling_frequency',
            field=models.IntegerField(default=30, verbose_name='Polling Frequency'),
        ),
        migrations.AlterField(
            model_name='node',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='node',
            name='push',
            field=models.BooleanField(default=False, verbose_name='Push'),
        ),
        migrations.AlterField(
            model_name='node',
            name='sync',
            field=models.BooleanField(default=False, verbose_name='Node Synchronized'),
        ),
    ]
