# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_auto_20160429_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='fernet_key',
            field=models.CharField(default='', max_length=64, verbose_name='Fernet key'),
        ),
    ]
