# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_node_fernet_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinterfaces',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='IP Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='polling_frequency',
            field=models.IntegerField(default=60, verbose_name='Polling Frequency'),
        ),
    ]
