# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0013_auto_20160511_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinterfaces',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.0.1', verbose_name='IP Address'),
        ),
    ]
