# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_auto_20160511_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='node_state',
        ),
        migrations.AddField(
            model_name='node',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='node',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
    ]
