# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_auto_20160513_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='polling_frequency',
        ),
        migrations.AddField(
            model_name='node',
            name='polling_interval',
            field=models.IntegerField(default=60, verbose_name='Polling Interval'),
        ),
    ]
