# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_auto_20160513_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='dist',
            field=models.CharField(default='', max_length=100, verbose_name='Node Distribution'),
        ),
        migrations.AlterField(
            model_name='node',
            name='dist_version',
            field=models.CharField(default='', max_length=50, verbose_name='Node Distribution Version'),
        ),
        migrations.AlterField(
            model_name='node',
            name='platform',
            field=models.CharField(choices=[('iptables', 'IPTables')], default='linux', max_length=30, verbose_name='Firewall Platform'),
        ),
        migrations.AlterField(
            model_name='node',
            name='python_version',
            field=models.CharField(default='', max_length=256, verbose_name='Python Version'),
        ),
    ]
