# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_auto_20160523_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pid', models.CharField(max_length=100, verbose_name='Process ID')),
                ('name', models.CharField(max_length=500, verbose_name='Process Name')),
                ('type', models.CharField(max_length=100, verbose_name='Process Type')),
                ('running', models.BooleanField(verbose_name='Running')),
                ('runningfor', models.CharField(max_length=250, verbose_name='Running For')),
                ('locked', models.BooleanField(verbose_name='Locked')),
                ('delete', models.BooleanField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
