# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_nodeprocess'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nodeprocess',
            table='node_processes',
        ),
    ]
