# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0019_auto_20160811_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeprocess',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nodeprocess',
            name='locked',
            field=models.BooleanField(default=True, verbose_name='Locked'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeprocess',
            unique_together=set([('node', 'name', 'type')]),
        ),
    ]
