# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0020_auto_20160811_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeprocess',
            name='ipaddr',
            field=models.CharField(default='*', max_length=500, verbose_name='IP Addresses'),
        ),
        migrations.AddField(
            model_name='nodeprocess',
            name='port',
            field=models.CharField(default='', max_length=50, verbose_name='Port'),
        ),
    ]
