# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0021_auto_20160812_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeprocess',
            name='lockable',
            field=models.BooleanField(default=False, verbose_name='Lockable'),
        ),
    ]
