# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0022_nodeprocess_lockable'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeprocess',
            name='category',
            field=models.CharField(default='unknown', max_length=100, verbose_name='Process Type Category'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeprocess',
            unique_together=set([('node', 'name')]),
        ),
        migrations.RemoveField(
            model_name='nodeprocess',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='nodeprocess',
            unique_together=set([('node', 'name', 'category')]),
        ),
    ]
