def makeCSS(fname=None):
    cssString='''img {
    position:absolute;
    top: 250px;
    left: 0px;
    border: 0;
}

body{
    font-family: 'Open Sans', sans-serif;
    font-size: 1.5em;
}

h2 {
    margin: 0px;
    padding: 0px;
    color: black;
    font-size: 2.5em;
    font-weight: 600;
}

h3 {
    margin: 0px;
    padding: 0px;
    color: black;
    font-size: 1.5em;
    font-weight: 500;
}

a:link {	
    color: black;
    font-weight: 700; 
    text-decoration: none;
}

a:visited {
    color: black;
    font-weight: 700; 
    text-decoration: none;
    border-bottom:0px dashed
}

a:hover{background: black;
    color: white;
    font-weight: 700;
}
'''
    if fname is not None:
        f=open(fname,"w")
        f.write(cssString)
        f.close()
    else:
        return(cssString)

def makeSCRIPT(ims):
    assert isinstance(ims, (list,tuple))
    imlst=json.dumps(ims)
    script='''<script>
    var images = {0};
    var numim = images.length;
    var index = 0;
    function setPicture()
    {{
        document.getElementById('imagetochange').src=images[index];
    }}
    function updatePicture()
    {{
        index=(index+1)\%numim
    }}
</script>
'''.format(imlst)
    return(script)

def makeHEAD(ims):
    head='''<head>
<meta charset=utf-8>
<title>QFA image browser generated by Colonyzer</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link rel="STYLESHEET" href="imbrowse.css" type="text/css">
'''
    head+=makeSCRIPT(ims)
    head+='''</head>
'''
    return(head)

import json

print(makeSCRIPT(["a","b","c"]))
print(makeHEAD(["a","b","c"]))
