language: python

sudo: false

cache:
    apt: true
    directories:
      - $HOME/.cache/pip

matrix:
  include:
    - python: '3.3'
    - python: '3.4'
    - python: '3.5'
      addons:
        apt:
          packages:
            - poppler-utils
            - imagemagick

install:
  - pip install tox-travis

script:
  - travis_wait 30 tox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
