
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "37ec2d708f904f9b034e7323cc82c80fdfc8846e",
 "version": "0.post.dev269"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
