name: numpy_indexed
channels:
  - anaconda
  - clinicalgraphics
dependencies:
  - python
  - numpy
  - future
  # dev
  - pyyaml =3.11*
  - invoke >=0.12*
  # tests
  - pytest >=2.8.4,<2.9
