
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = '834b5b23f7b3007b6a637cc4dfffdca3a8101c75'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

