# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: 4993fd66518a2c61c49b9e1bdf8f4b622459ee34 $
Configuration parameters:
  url = http://127.0.0.1:8080/wiki/
  name = vagrant

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'vagrant'
        self.langs = {
            'en': '127.0.0.1:8080',
        }

    def scriptpath(self, code):
        return {
            'en': '/w',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.26alpha',
        }[code]
