
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.18'
version_full = '340c45f2ec0c1866f2343dbca9b860272ed29242'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

