
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0a136a52d27045b8c0d4425f4df7a2a70f274361",
 "version": "0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
