
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0e4937fe20f60248a826a4558bd4645a1c2c0694",
 "version": "1.0.0b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
