
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c5e63b12ce42a155d010ae38b903718315370d58",
 "version": "1.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
