# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20151216_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockdown_slot_level', models.SmallIntegerField(default=160, verbose_name='Lockdown Slot Level')),
                ('polling_interval', models.PositiveIntegerField(default=60, verbose_name='Polling Interval')),
            ],
            options={
                'db_table': 'global_preferences',
            },
        ),
    ]
