
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6a74d8ba3f84d42da0a552e5ed4bc1a29ea19b11",
 "version": "0.post.dev319"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
