
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a1b29a736520cc368e2d6e2c7d5c31d5b637cbb6",
 "version": "2.10.105"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
