sudo: true

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -q
  - sudo apt-get install sox=14.3.2-3

# addons:
#   apt:
#     packages:
#     - sox

# command to install dependencies
install:
  - pip install coveralls
  - pip install -e .

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=sox -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y sox

after_failure:
    - pip uninstall -y sox