sudo: false
language: python
python:
- 2.7
- 3.5
script:
- pip install -U pytest
- python setup.py test
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: release
  password:
    secure: Inr0AkoZf5t3rcfJBslAynZ8jVGe77B7hxV6UD/PpgGdoKK1dPC13Brm59MNPTy/zQeCI+QFps9cV1G7jAw6CfMHwDfzsvmnhnkOdC+3N/8XFjxkzq0pLrZ+XztChldZZOOrD1IkJaHYBnuo9NALQQZ30nPIVLSlJIy31LP1hHjTt4I6b/xSbkPb9OCc5dzeieedcwN7dhBDCdjls+rLP5eyy2drpD99E7S820Pdl8nPqqTd6PkrCp3rxTnFDH/KDuIZ8PL40QAKz19+HSwTTe9Ic5O1HKSG7nVP98DvcCXuLZmNb/m8vj0ilagi1sdEs3QBbyNHBYteSnivPxjUSbR3cq1kjQ8aLXCb9Cc25sYRS+3R1k0ccjXrFPxpoUKdyMnRUOve3FbzlQsikuRdlZXP637O3XmRjQ8FmANEhwYyPqGcDgz1jHV31BaJsDlfzOM07wLFDGeV3ZcwWhLR7jUqgR3Wp4z5Gx4HDTNNkoHvaC99vtWJkIFJ7yBhDW1c+n6ZLIxwVNQ0Km8ZnRfKKkYVE3PSniB/9fglSDzbtILe/Dt+wMchFoFkNpyUcazUuPTxxhG0WuWAXQIcRGis6mklaurl1aNngGuIlE+K1bkf+BULtnAJLEa9rjeiGTtc3BgL/RtOfMU9EA57P1HMPru9zfvWimDXH3p/DcJrbcw=
