
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "008c52f483a1794385cc8b50f42994b40879041c",
 "version": "0.post.dev346"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
