language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
- pip install -r requirements.txt
- pip install pint
# command to run tests
script: 
  - nosetests --with-coverage --cover-package=hszinc --where=tests
after_success:
  - coveralls
