
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "82a66795ea74823b98dfa4f35c95b35279ab3f55",
 "version": "1.2.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
