
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bff6d3d00eeed9ad389d3fc278da1043227cda1e",
 "version": "1.2.53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
