
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1ebca88a75eb52fe4c2e35f9c410048126a4c108",
 "version": "2.10.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
