
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6b6a4b754fd8940e72ad1bb743fd92924a72029a",
 "version": "1.0.0.post.dev233"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
