
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f5e62dbf56d075715af4e7f8b89a0a89331937ba",
 "version": "1.0.0.post.dev224"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
