
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7ee0d2599f7a294f784323c5047853fff81a0b4d",
 "version": "1.0.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
