sudo: false
language: python
python:
- 2.7
- 3.5
script:
- pip install -U pytest
- python setup.py test
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: release
  password:
    secure: WEysgrnneZxB0sKlHyB17YBVjtJu8XGDtp3zztPDZkeRyuPsSTOeOp4zO1UGACQGAB4FMD2ID35aEesny+Mxwej+KkuW8g2MKznxEKSM7AjWHfelopRpj3bBI9M173wnPZm06y4f7/ZtnfYZUF5mYi9ObbB2VpCqgz/U7QDzL7TQOcNdXLMk7MRBsVXgLd9pXh+J0rpB2Tzjx8fwHhFh1eTA/g99mT4SEOqVoeqls9r44JjC5LlZ4r3k5vC+kZ6G+OeEzhTb0FVJCRsbGv5QuOuP3xeRQs4AgRLV/gXCIAI8VlmER+Hx1un/8Rv8a/kHebIZVDgavTHS9aIDWGa60iST8ICEb1QSJQgtPeTL5Hj9bWrw0dBOSSuj0a7GQlzaR2IyCY5YApsqXyxxIr6wqbR2LTX4+fRNFwWWaVaEc+crL0QRFZASGgi6jr1kaGD25TvEhERY9ZDdIw5F2g/27bwtFKtX169jG9zlFwrKp8YhTcnW2riZIOMjAMqPORq9u8C2AfwXKmvk85qoPNFF+9CkW/G/lX17pLPs9hPRKOfU4yG6TDv2SBWGXxJaZnoUiYm4Ayprxr2oE0C/8WuN8uwzqeAj9ZW76xQ7Z3cm9SBz5ehjT/0twhIlQaPlZek2AQ1QaRo7hh1W8w1Y0asKUXnY5KjC+dtTrJTU4IT/E2Y=
