
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e519149733eaa9f9938e72f4023a4d4f1a6a5f9d",
 "version": "1.0.0.post.dev125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
