language: python
branches:
  except:
  - gh-pages
matrix:
  include:
  - python: 3.4
    env: TOXENV=3.4,check,doc_travis
  - python: 2.7
    env: TOXENV=2.7,check,doc_travis
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y xsltproc
- sudo apt-get install -y genisoimage
- sudo apt-get install -y enchant
install:
- pip install -r .travis.requirements.txt
script:
- tox
after_success:
- tox -e doc_travis_deploy
deploy:
  provider: pypi
  user: suse
  password:
    secure: GzP6msQBtl6j1Nclnagm6pkUatxCIAIwZDKAlB5G0kXP9L/QzTpyXA9WCTiMgKiA+/Id9P1rTbSBJsP6zfD11gkU+cjbeXojCQjhng0r/Ot8Vavq1L1/sSL8Dl/adRxbm5VPkwttR6SuuvauPDVjQZiOBXP1sFjrghHSQtj6ZXNn0Vqy70DiPjCK8M2WiQiijpM9rC/jK2MW/kIXBr1ylVPIexqmj2YgzZ9IgnHWDSgslt4Hy+nU4GquFdIs3NTtJJTCkGSIFxnyXst0CxE5wsepoOIW/FBKFjtpcF/SWWjczszcwIzWt6Ddstkr5GAO0isQd2slTR1zshfP312dyV0uBfj3Rj/lcsCuvrJXfzdyWUsEGZHFcGq2AC+Mx7J57VWML2EDpVwDW1DQjMlzGtLiL0NKX9bSWC2k6GAoY56yoki2+KpLnKaBzq6iMyi8FjTWiTNHHfNO/YbmTcvSxwbkHqMUEBj84WxA2bRPkWy5MZ01iZnPP3wfN7HY/EZTACyZxWnhKQUmQB+hSBlxIaPGfyy5tNMwb8EozQqOt3fKWGi+9QJG8WC04qYpwc29GwJLJimXBPWKXmiADfiisyt4v6WJl9llcbLxwcEJTcW/hJWff2luiOSj1dURQss/iO2Ul0O/eRg34uGkHHP6G6LyrigNScwgVIYZu/toKH0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: SUSE/kiwi
