
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "087eec8b7173fd5b0aac9845419b3ae81119dc64",
 "version": "1.0.49"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
