name: lazy_git
dependencies:
- click=6.6=py35_0
- flask=0.11.1=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- nose=1.3.7=py35_1
- openssl=1.0.2h=1
- python=3.5.2=0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- tornado=4.3=py35_1
- werkzeug=0.11.10=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - flask-script==2.0.5
  - pip==8.1.2
  - sh==1.11
  - wheel==0.29.0

