heat_template_version: 2016-04-08

description: >
  OpenStack Redis service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  RedisBase:
    type: ../../database/redis-base.yaml

outputs:
  role_data:
    description: Role data for the Redis pacemaker role.
    value:
      config_settings:
        map_merge:
          - get_attr: [RedisBase, role_data, config_settings]
          - tripleo::profile::pacemaker::database::redis::redis_vip: {get_input: redis_vip}
            redis::service_manage: false
            redis::notify_service: false
      step_config: |
        include ::tripleo::profile::pacemaker::database::redis
