# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 19:36
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0002_auto_20151020_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablesbundleset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesbundleset',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptableschain',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptableschain',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptableschainset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptableschainset',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesdestination',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesdestination',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesfragment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesfragment',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesifacein',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesifacein',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesifaceout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesifaceout',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesjump',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesjump',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesjumpoptions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesjumpoptions',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesmatch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesmatch',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesmatchoptions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesmatchoptions',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesprotocol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesprotocol',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesring',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesring',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablessource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablessource',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=timezone.now()),
            preserve_default=False,
        ),
    ]
