# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0003_auto_20151216_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptablesrule',
            options={'ordering': ['sortId']},
        ),
    ]
