# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0004_auto_20160107_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptableschainset',
            options={'ordering': ['slot', 'sortId']},
        ),
    ]
