# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0005_auto_20160107_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptableschainset',
            name='slot',
            field=models.SmallIntegerField(choices=[(10, 'Administration'), (20, 'SD Server'), (30, 'Identity Servers'), (40, 'Update Servers'), (50, 'DNS Servers'), (60, 'NTP Servers'), (70, 'Node Custom Rules'), (1000, 'User Defined')], verbose_name='Chain Set Slot'),
        ),
    ]
