# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0006_auto_20160107_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptablesmatchoptions',
            options={'ordering': ['sortId']},
        ),
        migrations.AddField(
            model_name='iptablesmatchoptions',
            name='sortId',
            field=models.SmallIntegerField(default=1, verbose_name='Sort ID'),
            preserve_default=False,
        ),
    ]
