# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0007_auto_20160113_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptableschainset',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='iptableschainset',
            name='slot',
            field=models.SmallIntegerField(choices=[(110, 'Administration'), (120, 'SD Server'), (130, 'Identity Servers'), (140, 'Update Servers'), (150, 'DNS Servers'), (160, 'NTP Servers'), (170, 'Node Custom Rules'), (100, 'User Defined'), (980, 'Logging Rules'), (990, 'Rejection Rules')], verbose_name='Chain Set Slot'),
        ),
    ]
