# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0008_auto_20160125_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptablesdestination',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablesfragment',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablesifacein',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablesifaceout',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablesjump',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablesjumpoptions',
            name='jump',
        ),
        migrations.RemoveField(
            model_name='iptablesprotocol',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='iptablessource',
            name='rule',
        ),
        migrations.AlterModelOptions(
            name='iptablesmatchoptions',
            options={'ordering': ['sort_id']},
        ),
        migrations.AlterModelOptions(
            name='iptablesrule',
            options={'ordering': ['sort_id']},
        ),
        migrations.RenameField(
            model_name='iptablesmatchoptions',
            old_name='sortId',
            new_name='sort_id',
        ),
        migrations.RenameField(
            model_name='iptablesrule',
            old_name='sortId',
            new_name='sort_id',
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='dest_address',
            field=models.CharField(default='127.0.0.1', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='dest_invert',
            field=models.BooleanField(default=0, verbose_name='Invert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='dest_mask',
            field=models.SmallIntegerField(default=8, verbose_name='Mask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='fragment',
            field=models.BooleanField(default=False, verbose_name='Fragment'),
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='fragment_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='ifacein_name',
            field=models.CharField(default='lo', max_length=25, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='ifaceout_invert',
            field=models.BooleanField(default=0, verbose_name='Invert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='ifaceout_name',
            field=models.CharField(default='lo', max_length=25, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='infacein_invert',
            field=models.BooleanField(default=0, verbose_name='Invert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='ip_protocol_invert',
            field=models.BooleanField(default=0, verbose_name='Invert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='ip_protocol_name',
            field=models.CharField(choices=[('all', 'All'), ('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], default='tcp', max_length=25, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='jump_name',
            field=models.CharField(default='--reject-with', max_length=50, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='jump_target',
            field=models.CharField(default='ACCEPT', max_length=50, verbose_name='Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='jump_value',
            field=models.CharField(default='icmp-host-prohibited', max_length=255, verbose_name='Value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='source_address',
            field=models.CharField(default='127.0.0.1', max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='source_invert',
            field=models.BooleanField(default=0, verbose_name='Invert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptablesrule',
            name='source_mask',
            field=models.SmallIntegerField(default=8, verbose_name='Mask'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IPTablesDestination',
        ),
        migrations.DeleteModel(
            name='IPTablesFragment',
        ),
        migrations.DeleteModel(
            name='IPTablesIFaceIn',
        ),
        migrations.DeleteModel(
            name='IPTablesIFaceOut',
        ),
        migrations.DeleteModel(
            name='IPTablesJump',
        ),
        migrations.DeleteModel(
            name='IPTablesJumpOptions',
        ),
        migrations.DeleteModel(
            name='IPTablesProtocol',
        ),
        migrations.DeleteModel(
            name='IPTablesSource',
        ),
    ]
