# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0009_auto_20160128_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptableschainset',
            options={'ordering': ['slot', 'sort_id']},
        ),
        migrations.RenameField(
            model_name='iptableschainset',
            old_name='sortId',
            new_name='sort_id',
        ),
    ]
