# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0010_auto_20160129_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iptablesmatchoptions',
            old_name='matchName',
            new_name='match_name',
        ),
    ]
