# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0011_auto_20160129_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesmatchoptions',
            name='invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='dest_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='ifaceout_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='infacein_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='ip_protocol_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='source_invert',
            field=models.BooleanField(default=False, verbose_name='Invert'),
        ),
    ]
