# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0012_auto_20160129_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iptablesrule',
            old_name='infacein_invert',
            new_name='ifacein_invert',
        ),
    ]
