# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0013_auto_20160130_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTablesJump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=50, verbose_name='Target')),
            ],
            options={
                'db_table': 'iptables_jump',
            },
        ),
        migrations.CreateModel(
            name='IPTablesJumpOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Value')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('jump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='iptables.IPTablesJump')),
            ],
            options={
                'db_table': 'iptables_jump_options',
            },
        ),
        migrations.RemoveField(
            model_name='iptablesrule',
            name='jump_name',
        ),
        migrations.RemoveField(
            model_name='iptablesrule',
            name='jump_target',
        ),
        migrations.RemoveField(
            model_name='iptablesrule',
            name='jump_value',
        ),
        migrations.AddField(
            model_name='iptablesjump',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jump', to='iptables.IPTablesRule'),
        ),
    ]
