# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0014_auto_20160203_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesring',
            name='version',
            field=models.CharField(choices=[(1, 'ipv4'), (2, 'ipv6'), (3, 'both')], max_length=4, verbose_name='Transport Version'),
        ),
    ]
