# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_bundle_default'),
        ('iptables', '0015_auto_20160224_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTablesMachineSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='rules.Bundle')),
            ],
            options={
                'db_table': 'iptables_machine_set',
            },
        ),
        migrations.RenameModel(
            old_name='IPTablesChainSet',
            new_name='IPTablesMachineSubset',
        ),
        migrations.RemoveField(
            model_name='iptablesbundleset',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='iptablesbundleset',
            name='chainset',
        ),
        migrations.RenameField(
            model_name='iptableschain',
            old_name='chainset',
            new_name='machine_subset',
        ),
        migrations.AlterModelTable(
            name='iptablesmachinesubset',
            table='iptables_machine_subset',
        ),
        migrations.DeleteModel(
            name='IPTablesBundleSet',
        ),
        migrations.AddField(
            model_name='iptablesmachineset',
            name='machine_subset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_sets', to='iptables.IPTablesMachineSubset'),
        ),
    ]
