# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0016_auto_20160226_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablesmachineset',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
