# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0017_iptablesmachineset_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablesmachineset',
            name='panic',
            field=models.BooleanField(default=False, verbose_name='Panic'),
        ),
    ]
