# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0018_iptablesmachineset_panic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesjumpoptions',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='iptablesjumpoptions',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4000, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='sort_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sort ID'),
        ),
        migrations.AlterField(
            model_name='iptablesmatch',
            name='name',
            field=models.CharField(blank=True, choices=[('state', 'State')], max_length=50, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='iptablesmatchoptions',
            name='option',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='iptablesmatchoptions',
            name='sort_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sort ID'),
        ),
        migrations.AlterField(
            model_name='iptablesmatchoptions',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='dest_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='dest_mask',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mask'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='ifacein_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='ifaceout_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='ip_protocol_name',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], max_length=25, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='sort_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sort ID'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='source_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='iptablesrule',
            name='source_mask',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Mask'),
        ),
    ]
