# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0019_auto_20160422_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='slot',
            field=models.SmallIntegerField(choices=[(110, 'Administration'), (120, 'SD Server'), (130, 'DNS Servers'), (140, 'NTP Servers'), (150, 'Update Servers'), (160, 'Identity Servers'), (170, 'Node Custom Rules'), (200, 'User Defined'), (980, 'Logging Rules'), (990, 'Rejection Rules')], verbose_name='Chain Set Slot'),
        ),
    ]
