# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0020_auto_20160513_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='slot',
            field=models.SmallIntegerField(choices=[(110, 'Administration'), (120, 'SD Server'), (130, 'DNS Servers'), (140, 'NTP Servers'), (150, 'Update Servers'), (160, 'Identity Servers'), (1000, 'Node Custom Rules'), (2000, 'User Defined'), (9000, 'Reserved'), (9800, 'Logging Rules'), (9900, 'Rejection Rules')], verbose_name='Chain Set Slot'),
        ),
    ]
