# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0021_auto_20160523_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptablesmachinesubset',
            name='slot',
            field=models.SmallIntegerField(choices=[(110, 'Administration'), (130, 'Dynamic Name Service'), (140, 'Network Time Protocol'), (150, 'System Update'), (160, 'Identity Services'), (2000, 'User Defined'), (9800, 'Logging Rules'), (9900, 'Rejection Rules')], verbose_name='Chain Set Slot'),
        ),
    ]
