# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0022_auto_20160525_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iptablesmachinesubset',
            old_name='desc',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='iptablesrule',
            old_name='desc',
            new_name='descr',
        ),
    ]
