# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0023_auto_20160617_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptablesmatch',
            name='invertible',
            field=models.BooleanField(default=False, verbose_name='Invertible'),
        ),
        migrations.AlterField(
            model_name='iptablesmatch',
            name='name',
            field=models.CharField(blank=True, choices=[('state', 'State')], max_length=50, null=True, verbose_name='Name'),
        ),
    ]
