# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptables', '0024_auto_20160624_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptablesmatch',
            name='invertible',
        ),
        migrations.AddField(
            model_name='iptablesmatchoptions',
            name='invertible',
            field=models.BooleanField(default=False, verbose_name='Invertible'),
        ),
    ]
