
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9982edd9f86a9735808201bf852204bf09c12bdc",
 "version": "1.2.51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
