
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2cff52022160b295deef5e52da843f0b771176ee",
 "version": "1.2.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
