
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "81d4e40b731c4ed67e8818ce1a21859249ea47d1",
 "version": "0.4.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
