
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "965feb60db1b3c96c5e13e3774190201138698bb",
 "version": "0.5.1b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
