
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "be716cf4b3e1e35ad5ea9be27fc3906d1f15829b",
 "version": "1.0.0.post.dev235"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
