
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "73d32405f6b85004820c177cb202675252df894f",
 "version": "0.post.dev321"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
