
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.7.3',
    'branch_nick': '(no',
    'revision_id': 'cf652970c622b0d909bcfeac03b77ca50b1e8994',
    'revno': 4374
}
