
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7e4528cd5c9d4e00c87230f6f89b592297b9e014",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
