
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "81d1a4dfed9c1b111fbee5474bd3c6a1e7ce2e7f",
 "version": "2.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
