# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgapp', '0002_organization_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
