
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c017b4e9c9445d25f8b83e75dcf6191322266a54",
 "version": "1.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
