heat_template_version: 2016-04-08

description: >
  Configuration details for MongoDB service using composable roles

parameters:
  MongoDbNoJournal:
    default: false
    description: Should MongoDb journaling be disabled
    type: boolean
  MongoDbIPv6:
    default: false
    description: Enable IPv6 if MongoDB VIP is IPv6
    type: boolean
  MongoDbReplset:
    type: string
    default: "tripleo"

outputs:
  aux_parameters:
    description: Additional parameters referenced outside the base file
    value:
      rplset_name: {get_param: MongoDbReplset}
  role_data:
    description: Role data for the MongoDB base service.
    value:
      config_settings:
        mongodb::server::nojournal: {get_param: MongoDbNoJournal}
        mongodb::server::ipv6: {get_param: MongoDbIPv6}
        mongodb::server::replset: {get_param: MongoDbReplset}