heat_template_version: 2016-04-08

description: >
  OpenStack Redis service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  RedisBase:
    type: ./redis-base.yaml

outputs:
  role_data:
    description: Role data for the redis role.
    value:
      config_settings:
        map_merge:
          - get_attr: [RedisBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::database::redis
