heat_template_version: 2016-04-08

description: >
  OpenStack Redis service configured with Puppet

parameters:
  RedisPassword:
    description: The password for Redis
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the redis role.
    value:
      config_settings:
       redis::requirepass: {get_param: RedisPassword}
       redis::masterauth: {get_param: RedisPassword}
       redis::sentinel_auth_pass: {get_param: RedisPassword}
       tripleo::loadbalancer::redis_password: {get_param: RedisPassword}

