# This file was auto-generated by salt's setup on Monday, 25 July 2016 @ 20:07:05 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 11, 0, 0, 0, None)
