
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c4ac7c84b74588e4ef70d1c9f5617cbb6d9f0659",
 "version": "1.0.0.post.dev103"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
