#!/usr/bin/env python3

from datetime import datetime


def writetofile(data, path="./", var="simpleDom"):

    prepend = "/* generated by simple-engine {0} */\n".format(datetime.now().time())
    largedata = "{0}var {1} = {2};".format(prepend, var, data)

    with open(path, "w") as f:
        f.write(largedata)
