
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ad1ce37fe82cdfa75a8193566c7c7cdcae07b09c",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
