
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b59c0027796448595af3670103d8b05538e1f266",
 "version": "0.7.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
