# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pydart2_api', [dirname(__file__)])
        except ImportError:
            import _pydart2_api
            return _pydart2_api
        if fp is not None:
            try:
                _mod = imp.load_module('_pydart2_api', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pydart2_api = swig_import_helper()
    del swig_import_helper
else:
    import _pydart2_api
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def init(verbose=True):
    return _pydart2_api.init(verbose)
init = _pydart2_api.init

def destroy():
    return _pydart2_api.destroy()
destroy = _pydart2_api.destroy

def setVerbose(verbose=True):
    return _pydart2_api.setVerbose(verbose)
setVerbose = _pydart2_api.setVerbose

def getVerbose():
    return _pydart2_api.getVerbose()
getVerbose = _pydart2_api.getVerbose

def createWorld(timestep):
    return _pydart2_api.createWorld(timestep)
createWorld = _pydart2_api.createWorld

def createWorldFromSkel(path):
    return _pydart2_api.createWorldFromSkel(path)
createWorldFromSkel = _pydart2_api.createWorldFromSkel

def destroyWorld(wid):
    return _pydart2_api.destroyWorld(wid)
destroyWorld = _pydart2_api.destroyWorld

def world__addSkeleton(wid, path):
    return _pydart2_api.world__addSkeleton(wid, path)
world__addSkeleton = _pydart2_api.world__addSkeleton

def world__getNumSkeletons(wid):
    return _pydart2_api.world__getNumSkeletons(wid)
world__getNumSkeletons = _pydart2_api.world__getNumSkeletons

def world__reset(wid):
    return _pydart2_api.world__reset(wid)
world__reset = _pydart2_api.world__reset

def world__step(wid):
    return _pydart2_api.world__step(wid)
world__step = _pydart2_api.world__step

def world__render(wid):
    return _pydart2_api.world__render(wid)
world__render = _pydart2_api.world__render

def world__setTimeStep(wid, _timeStep):
    return _pydart2_api.world__setTimeStep(wid, _timeStep)
world__setTimeStep = _pydart2_api.world__setTimeStep

def world__getTimeStep(wid):
    return _pydart2_api.world__getTimeStep(wid)
world__getTimeStep = _pydart2_api.world__getTimeStep

def world__setTime(wid, _time):
    return _pydart2_api.world__setTime(wid, _time)
world__setTime = _pydart2_api.world__setTime

def world__getTime(wid):
    return _pydart2_api.world__getTime(wid)
world__getTime = _pydart2_api.world__getTime

def world__getSimFrames(wid):
    return _pydart2_api.world__getSimFrames(wid)
world__getSimFrames = _pydart2_api.world__getSimFrames

def world__getIndex(wid, _index):
    return _pydart2_api.world__getIndex(wid, _index)
world__getIndex = _pydart2_api.world__getIndex

def world__setGravity(wid, inv3):
    return _pydart2_api.world__setGravity(wid, inv3)
world__setGravity = _pydart2_api.world__setGravity

def world__getGravity(wid):
    return _pydart2_api.world__getGravity(wid)
world__getGravity = _pydart2_api.world__getGravity

def skeleton__render(wid, skid):
    return _pydart2_api.skeleton__render(wid, skid)
skeleton__render = _pydart2_api.skeleton__render

def skeleton__renderWithColor(wid, skid, inv4):
    return _pydart2_api.skeleton__renderWithColor(wid, skid, inv4)
skeleton__renderWithColor = _pydart2_api.skeleton__renderWithColor

def skeleton__getName(wid, skid):
    return _pydart2_api.skeleton__getName(wid, skid)
skeleton__getName = _pydart2_api.skeleton__getName

def skeleton__getMass(wid, skid):
    return _pydart2_api.skeleton__getMass(wid, skid)
skeleton__getMass = _pydart2_api.skeleton__getMass

def skeleton__isMobile(wid, skid):
    return _pydart2_api.skeleton__isMobile(wid, skid)
skeleton__isMobile = _pydart2_api.skeleton__isMobile

def skeleton__setMobile(wid, skid, mobile):
    return _pydart2_api.skeleton__setMobile(wid, skid, mobile)
skeleton__setMobile = _pydart2_api.skeleton__setMobile

def skeleton__getSelfCollisionCheck(wid, skid):
    return _pydart2_api.skeleton__getSelfCollisionCheck(wid, skid)
skeleton__getSelfCollisionCheck = _pydart2_api.skeleton__getSelfCollisionCheck

def skeleton__setSelfCollisionCheck(wid, skid, enable):
    return _pydart2_api.skeleton__setSelfCollisionCheck(wid, skid, enable)
skeleton__setSelfCollisionCheck = _pydart2_api.skeleton__setSelfCollisionCheck

def skeleton__getAdjacentBodyCheck(wid, skid):
    return _pydart2_api.skeleton__getAdjacentBodyCheck(wid, skid)
skeleton__getAdjacentBodyCheck = _pydart2_api.skeleton__getAdjacentBodyCheck

def skeleton__setAdjacentBodyCheck(wid, skid, enable):
    return _pydart2_api.skeleton__setAdjacentBodyCheck(wid, skid, enable)
skeleton__setAdjacentBodyCheck = _pydart2_api.skeleton__setAdjacentBodyCheck

def skeleton__setRootJointToTransAndEuler(wid, skid):
    return _pydart2_api.skeleton__setRootJointToTransAndEuler(wid, skid)
skeleton__setRootJointToTransAndEuler = _pydart2_api.skeleton__setRootJointToTransAndEuler

def skeleton__getNumBodyNodes(wid, skid):
    return _pydart2_api.skeleton__getNumBodyNodes(wid, skid)
skeleton__getNumBodyNodes = _pydart2_api.skeleton__getNumBodyNodes

def skeleton__getNumJoints(wid, skid):
    return _pydart2_api.skeleton__getNumJoints(wid, skid)
skeleton__getNumJoints = _pydart2_api.skeleton__getNumJoints

def skeleton__getNumDofs(wid, skid):
    return _pydart2_api.skeleton__getNumDofs(wid, skid)
skeleton__getNumDofs = _pydart2_api.skeleton__getNumDofs

def skeleton__getNumMarkers(wid, skid):
    return _pydart2_api.skeleton__getNumMarkers(wid, skid)
skeleton__getNumMarkers = _pydart2_api.skeleton__getNumMarkers

def skeleton__getPositions(wid, skid, outv):
    return _pydart2_api.skeleton__getPositions(wid, skid, outv)
skeleton__getPositions = _pydart2_api.skeleton__getPositions

def skeleton__setPositions(wid, skid, inv):
    return _pydart2_api.skeleton__setPositions(wid, skid, inv)
skeleton__setPositions = _pydart2_api.skeleton__setPositions

def skeleton__getVelocities(wid, skid, outv):
    return _pydart2_api.skeleton__getVelocities(wid, skid, outv)
skeleton__getVelocities = _pydart2_api.skeleton__getVelocities

def skeleton__setVelocities(wid, skid, inv):
    return _pydart2_api.skeleton__setVelocities(wid, skid, inv)
skeleton__setVelocities = _pydart2_api.skeleton__setVelocities

def skeleton__setForces(wid, skid, inv):
    return _pydart2_api.skeleton__setForces(wid, skid, inv)
skeleton__setForces = _pydart2_api.skeleton__setForces

def skeleton__getPositionDifferences(wid, skid, inv1, inv2, outv):
    return _pydart2_api.skeleton__getPositionDifferences(wid, skid, inv1, inv2, outv)
skeleton__getPositionDifferences = _pydart2_api.skeleton__getPositionDifferences

def skeleton__getVelocityDifferences(wid, skid, inv1, inv2, outv):
    return _pydart2_api.skeleton__getVelocityDifferences(wid, skid, inv1, inv2, outv)
skeleton__getVelocityDifferences = _pydart2_api.skeleton__getVelocityDifferences

def skeleton__getPositionLowerLimits(wid, skid, outv):
    return _pydart2_api.skeleton__getPositionLowerLimits(wid, skid, outv)
skeleton__getPositionLowerLimits = _pydart2_api.skeleton__getPositionLowerLimits

def skeleton__getPositionUpperLimits(wid, skid, outv):
    return _pydart2_api.skeleton__getPositionUpperLimits(wid, skid, outv)
skeleton__getPositionUpperLimits = _pydart2_api.skeleton__getPositionUpperLimits

def skeleton__getForceLowerLimits(wid, skid, outv):
    return _pydart2_api.skeleton__getForceLowerLimits(wid, skid, outv)
skeleton__getForceLowerLimits = _pydart2_api.skeleton__getForceLowerLimits

def skeleton__getForceUpperLimits(wid, skid, outv):
    return _pydart2_api.skeleton__getForceUpperLimits(wid, skid, outv)
skeleton__getForceUpperLimits = _pydart2_api.skeleton__getForceUpperLimits

def skeleton__getCOM(wid, skid):
    return _pydart2_api.skeleton__getCOM(wid, skid)
skeleton__getCOM = _pydart2_api.skeleton__getCOM

def skeleton__getCOMLinearVelocity(wid, skid):
    return _pydart2_api.skeleton__getCOMLinearVelocity(wid, skid)
skeleton__getCOMLinearVelocity = _pydart2_api.skeleton__getCOMLinearVelocity

def skeleton__getCOMLinearAcceleration(wid, skid):
    return _pydart2_api.skeleton__getCOMLinearAcceleration(wid, skid)
skeleton__getCOMLinearAcceleration = _pydart2_api.skeleton__getCOMLinearAcceleration

def skeleton__getMassMatrix(wid, skid, outm):
    return _pydart2_api.skeleton__getMassMatrix(wid, skid, outm)
skeleton__getMassMatrix = _pydart2_api.skeleton__getMassMatrix

def skeleton__getCoriolisAndGravityForces(wid, skid, outv):
    return _pydart2_api.skeleton__getCoriolisAndGravityForces(wid, skid, outv)
skeleton__getCoriolisAndGravityForces = _pydart2_api.skeleton__getCoriolisAndGravityForces

def skeleton__getConstraintForces(wid, skid, outv):
    return _pydart2_api.skeleton__getConstraintForces(wid, skid, outv)
skeleton__getConstraintForces = _pydart2_api.skeleton__getConstraintForces

def bodynode__getName(wid, skid, bid):
    return _pydart2_api.bodynode__getName(wid, skid, bid)
bodynode__getName = _pydart2_api.bodynode__getName

def bodynode__getParentBodyNode(wid, skid, bid):
    return _pydart2_api.bodynode__getParentBodyNode(wid, skid, bid)
bodynode__getParentBodyNode = _pydart2_api.bodynode__getParentBodyNode

def bodynode__getNumChildBodyNodes(wid, skid, bid):
    return _pydart2_api.bodynode__getNumChildBodyNodes(wid, skid, bid)
bodynode__getNumChildBodyNodes = _pydart2_api.bodynode__getNumChildBodyNodes

def bodynode__getChildBodyNode(wid, skid, bid, _index):
    return _pydart2_api.bodynode__getChildBodyNode(wid, skid, bid, _index)
bodynode__getChildBodyNode = _pydart2_api.bodynode__getChildBodyNode

def bodynode__getParentJoint(wid, skid, bid):
    return _pydart2_api.bodynode__getParentJoint(wid, skid, bid)
bodynode__getParentJoint = _pydart2_api.bodynode__getParentJoint

def bodynode__getNumChildJoints(wid, skid, bid):
    return _pydart2_api.bodynode__getNumChildJoints(wid, skid, bid)
bodynode__getNumChildJoints = _pydart2_api.bodynode__getNumChildJoints

def bodynode__getChildJoint(wid, skid, bid, _index):
    return _pydart2_api.bodynode__getChildJoint(wid, skid, bid, _index)
bodynode__getChildJoint = _pydart2_api.bodynode__getChildJoint

def bodynode__getNumDependentDofs(wid, skid, bid):
    return _pydart2_api.bodynode__getNumDependentDofs(wid, skid, bid)
bodynode__getNumDependentDofs = _pydart2_api.bodynode__getNumDependentDofs

def bodynode__getDependentDof(wid, skid, bid, _index):
    return _pydart2_api.bodynode__getDependentDof(wid, skid, bid, _index)
bodynode__getDependentDof = _pydart2_api.bodynode__getDependentDof

def bodynode__getIndexInSkeleton(wid, skid, bid):
    return _pydart2_api.bodynode__getIndexInSkeleton(wid, skid, bid)
bodynode__getIndexInSkeleton = _pydart2_api.bodynode__getIndexInSkeleton

def bodynode__getIndexInTree(wid, skid, bid):
    return _pydart2_api.bodynode__getIndexInTree(wid, skid, bid)
bodynode__getIndexInTree = _pydart2_api.bodynode__getIndexInTree

def bodynode__getTreeIndex(wid, skid, bid):
    return _pydart2_api.bodynode__getTreeIndex(wid, skid, bid)
bodynode__getTreeIndex = _pydart2_api.bodynode__getTreeIndex

def bodynode__setGravityMode(wid, skid, bid, _gravityMode):
    return _pydart2_api.bodynode__setGravityMode(wid, skid, bid, _gravityMode)
bodynode__setGravityMode = _pydart2_api.bodynode__setGravityMode

def bodynode__getGravityMode(wid, skid, bid):
    return _pydart2_api.bodynode__getGravityMode(wid, skid, bid)
bodynode__getGravityMode = _pydart2_api.bodynode__getGravityMode

def bodynode__isCollidable(wid, skid, bid):
    return _pydart2_api.bodynode__isCollidable(wid, skid, bid)
bodynode__isCollidable = _pydart2_api.bodynode__isCollidable

def bodynode__setCollidable(wid, skid, bid, _isCollidable):
    return _pydart2_api.bodynode__setCollidable(wid, skid, bid, _isCollidable)
bodynode__setCollidable = _pydart2_api.bodynode__setCollidable

def bodynode__getMass(wid, skid, bid):
    return _pydart2_api.bodynode__getMass(wid, skid, bid)
bodynode__getMass = _pydart2_api.bodynode__getMass

def bodynode__getInertia(wid, skid, bid):
    return _pydart2_api.bodynode__getInertia(wid, skid, bid)
bodynode__getInertia = _pydart2_api.bodynode__getInertia

def bodynode__getLocalCOM(wid, skid, bid):
    return _pydart2_api.bodynode__getLocalCOM(wid, skid, bid)
bodynode__getLocalCOM = _pydart2_api.bodynode__getLocalCOM

def bodynode__getCOM(wid, skid, bid):
    return _pydart2_api.bodynode__getCOM(wid, skid, bid)
bodynode__getCOM = _pydart2_api.bodynode__getCOM

def bodynode__getCOMLinearVelocity(wid, skid, bid):
    return _pydart2_api.bodynode__getCOMLinearVelocity(wid, skid, bid)
bodynode__getCOMLinearVelocity = _pydart2_api.bodynode__getCOMLinearVelocity

def bodynode__getCOMSpatialVelocity(wid, skid, bid):
    return _pydart2_api.bodynode__getCOMSpatialVelocity(wid, skid, bid)
bodynode__getCOMSpatialVelocity = _pydart2_api.bodynode__getCOMSpatialVelocity

def bodynode__getCOMLinearAcceleration(wid, skid, bid):
    return _pydart2_api.bodynode__getCOMLinearAcceleration(wid, skid, bid)
bodynode__getCOMLinearAcceleration = _pydart2_api.bodynode__getCOMLinearAcceleration

def bodynode__getCOMSpatialAcceleration(wid, skid, bid):
    return _pydart2_api.bodynode__getCOMSpatialAcceleration(wid, skid, bid)
bodynode__getCOMSpatialAcceleration = _pydart2_api.bodynode__getCOMSpatialAcceleration

def bodynode__setFrictionCoeff(wid, skid, bid, _coeff):
    return _pydart2_api.bodynode__setFrictionCoeff(wid, skid, bid, _coeff)
bodynode__setFrictionCoeff = _pydart2_api.bodynode__setFrictionCoeff

def bodynode__getFrictionCoeff(wid, skid, bid):
    return _pydart2_api.bodynode__getFrictionCoeff(wid, skid, bid)
bodynode__getFrictionCoeff = _pydart2_api.bodynode__getFrictionCoeff

def bodynode__setRestitutionCoeff(wid, skid, bid, _coeff):
    return _pydart2_api.bodynode__setRestitutionCoeff(wid, skid, bid, _coeff)
bodynode__setRestitutionCoeff = _pydart2_api.bodynode__setRestitutionCoeff

def bodynode__getRestitutionCoeff(wid, skid, bid):
    return _pydart2_api.bodynode__getRestitutionCoeff(wid, skid, bid)
bodynode__getRestitutionCoeff = _pydart2_api.bodynode__getRestitutionCoeff

def bodynode__getTransform(wid, skid, bid):
    return _pydart2_api.bodynode__getTransform(wid, skid, bid)
bodynode__getTransform = _pydart2_api.bodynode__getTransform

def bodynode__getWorldTransform(wid, skid, bid):
    return _pydart2_api.bodynode__getWorldTransform(wid, skid, bid)
bodynode__getWorldTransform = _pydart2_api.bodynode__getWorldTransform

def bodynode__getRelativeTransform(wid, skid, bid):
    return _pydart2_api.bodynode__getRelativeTransform(wid, skid, bid)
bodynode__getRelativeTransform = _pydart2_api.bodynode__getRelativeTransform

def bodynode__addExtForce(wid, skid, bid, inv3, inv3_2, _isForceLocal, _isOffsetLocal):
    return _pydart2_api.bodynode__addExtForce(wid, skid, bid, inv3, inv3_2, _isForceLocal, _isOffsetLocal)
bodynode__addExtForce = _pydart2_api.bodynode__addExtForce

def bodynode__setExtForce(wid, skid, bid, inv3, inv3_2, _isForceLocal, _isOffsetLocal):
    return _pydart2_api.bodynode__setExtForce(wid, skid, bid, inv3, inv3_2, _isForceLocal, _isOffsetLocal)
bodynode__setExtForce = _pydart2_api.bodynode__setExtForce

def bodynode__addExtTorque(wid, skid, bid, inv3, _isLocal):
    return _pydart2_api.bodynode__addExtTorque(wid, skid, bid, inv3, _isLocal)
bodynode__addExtTorque = _pydart2_api.bodynode__addExtTorque

def bodynode__setExtTorque(wid, skid, bid, inv3, _isLocal):
    return _pydart2_api.bodynode__setExtTorque(wid, skid, bid, inv3, _isLocal)
bodynode__setExtTorque = _pydart2_api.bodynode__setExtTorque

def dof__getName(wid, skid, dofid):
    return _pydart2_api.dof__getName(wid, skid, dofid)
dof__getName = _pydart2_api.dof__getName

def dof__getIndexInSkeleton(wid, skid, dofid):
    return _pydart2_api.dof__getIndexInSkeleton(wid, skid, dofid)
dof__getIndexInSkeleton = _pydart2_api.dof__getIndexInSkeleton

def dof__getIndexInTree(wid, skid, dofid):
    return _pydart2_api.dof__getIndexInTree(wid, skid, dofid)
dof__getIndexInTree = _pydart2_api.dof__getIndexInTree

def dof__getIndexInJoint(wid, skid, dofid):
    return _pydart2_api.dof__getIndexInJoint(wid, skid, dofid)
dof__getIndexInJoint = _pydart2_api.dof__getIndexInJoint

def dof__getTreeIndex(wid, skid, dofid):
    return _pydart2_api.dof__getTreeIndex(wid, skid, dofid)
dof__getTreeIndex = _pydart2_api.dof__getTreeIndex

def dof__getPosition(wid, skid, dofid):
    return _pydart2_api.dof__getPosition(wid, skid, dofid)
dof__getPosition = _pydart2_api.dof__getPosition

def dof__setPosition(wid, skid, dofid, _position):
    return _pydart2_api.dof__setPosition(wid, skid, dofid, _position)
dof__setPosition = _pydart2_api.dof__setPosition

def dof__getInitialPosition(wid, skid, dofid):
    return _pydart2_api.dof__getInitialPosition(wid, skid, dofid)
dof__getInitialPosition = _pydart2_api.dof__getInitialPosition

def dof__setInitialPosition(wid, skid, dofid, _initial):
    return _pydart2_api.dof__setInitialPosition(wid, skid, dofid, _initial)
dof__setInitialPosition = _pydart2_api.dof__setInitialPosition

def dof__hasPositionLimit(wid, skid, dofid):
    return _pydart2_api.dof__hasPositionLimit(wid, skid, dofid)
dof__hasPositionLimit = _pydart2_api.dof__hasPositionLimit

def dof__getPositionLowerLimit(wid, skid, dofid):
    return _pydart2_api.dof__getPositionLowerLimit(wid, skid, dofid)
dof__getPositionLowerLimit = _pydart2_api.dof__getPositionLowerLimit

def dof__setPositionLowerLimit(wid, skid, dofid, _limit):
    return _pydart2_api.dof__setPositionLowerLimit(wid, skid, dofid, _limit)
dof__setPositionLowerLimit = _pydart2_api.dof__setPositionLowerLimit

def dof__getPositionUpperLimit(wid, skid, dofid):
    return _pydart2_api.dof__getPositionUpperLimit(wid, skid, dofid)
dof__getPositionUpperLimit = _pydart2_api.dof__getPositionUpperLimit

def dof__setPositionUpperLimit(wid, skid, dofid, _limit):
    return _pydart2_api.dof__setPositionUpperLimit(wid, skid, dofid, _limit)
dof__setPositionUpperLimit = _pydart2_api.dof__setPositionUpperLimit

def dof__getVelocity(wid, skid, dofid):
    return _pydart2_api.dof__getVelocity(wid, skid, dofid)
dof__getVelocity = _pydart2_api.dof__getVelocity

def dof__setVelocity(wid, skid, dofid, _velocity):
    return _pydart2_api.dof__setVelocity(wid, skid, dofid, _velocity)
dof__setVelocity = _pydart2_api.dof__setVelocity

def dof__getInitialVelocity(wid, skid, dofid):
    return _pydart2_api.dof__getInitialVelocity(wid, skid, dofid)
dof__getInitialVelocity = _pydart2_api.dof__getInitialVelocity

def dof__setInitialVelocity(wid, skid, dofid, _initial):
    return _pydart2_api.dof__setInitialVelocity(wid, skid, dofid, _initial)
dof__setInitialVelocity = _pydart2_api.dof__setInitialVelocity

def dof__getVelocityLowerLimit(wid, skid, dofid):
    return _pydart2_api.dof__getVelocityLowerLimit(wid, skid, dofid)
dof__getVelocityLowerLimit = _pydart2_api.dof__getVelocityLowerLimit

def dof__setVelocityLowerLimit(wid, skid, dofid, _limit):
    return _pydart2_api.dof__setVelocityLowerLimit(wid, skid, dofid, _limit)
dof__setVelocityLowerLimit = _pydart2_api.dof__setVelocityLowerLimit

def dof__getVelocityUpperLimit(wid, skid, dofid):
    return _pydart2_api.dof__getVelocityUpperLimit(wid, skid, dofid)
dof__getVelocityUpperLimit = _pydart2_api.dof__getVelocityUpperLimit

def dof__setVelocityUpperLimit(wid, skid, dofid, _limit):
    return _pydart2_api.dof__setVelocityUpperLimit(wid, skid, dofid, _limit)
dof__setVelocityUpperLimit = _pydart2_api.dof__setVelocityUpperLimit

def joint__getName(wid, skid, jid):
    return _pydart2_api.joint__getName(wid, skid, jid)
joint__getName = _pydart2_api.joint__getName

def joint__setName(wid, skid, jid, _name, _renameDofs):
    return _pydart2_api.joint__setName(wid, skid, jid, _name, _renameDofs)
joint__setName = _pydart2_api.joint__setName

def joint__isKinematic(wid, skid, jid):
    return _pydart2_api.joint__isKinematic(wid, skid, jid)
joint__isKinematic = _pydart2_api.joint__isKinematic

def joint__isDynamic(wid, skid, jid):
    return _pydart2_api.joint__isDynamic(wid, skid, jid)
joint__isDynamic = _pydart2_api.joint__isDynamic

def joint__getParentBodyNode(wid, skid, jid):
    return _pydart2_api.joint__getParentBodyNode(wid, skid, jid)
joint__getParentBodyNode = _pydart2_api.joint__getParentBodyNode

def joint__getChildBodyNode(wid, skid, jid):
    return _pydart2_api.joint__getChildBodyNode(wid, skid, jid)
joint__getChildBodyNode = _pydart2_api.joint__getChildBodyNode

def joint__setTransformFromParentBodyNode(wid, skid, jid, inv44):
    return _pydart2_api.joint__setTransformFromParentBodyNode(wid, skid, jid, inv44)
joint__setTransformFromParentBodyNode = _pydart2_api.joint__setTransformFromParentBodyNode

def joint__setTransformFromChildBodyNode(wid, skid, jid, inv44):
    return _pydart2_api.joint__setTransformFromChildBodyNode(wid, skid, jid, inv44)
joint__setTransformFromChildBodyNode = _pydart2_api.joint__setTransformFromChildBodyNode

def joint__getTransformFromParentBodyNode(wid, skid, jid):
    return _pydart2_api.joint__getTransformFromParentBodyNode(wid, skid, jid)
joint__getTransformFromParentBodyNode = _pydart2_api.joint__getTransformFromParentBodyNode

def joint__getTransformFromChildBodyNode(wid, skid, jid):
    return _pydart2_api.joint__getTransformFromChildBodyNode(wid, skid, jid)
joint__getTransformFromChildBodyNode = _pydart2_api.joint__getTransformFromChildBodyNode

def joint__getDof(wid, skid, jid, _index):
    return _pydart2_api.joint__getDof(wid, skid, jid, _index)
joint__getDof = _pydart2_api.joint__getDof

def joint__getNumDofs(wid, skid, jid):
    return _pydart2_api.joint__getNumDofs(wid, skid, jid)
joint__getNumDofs = _pydart2_api.joint__getNumDofs

def marker__getBodyNode(wid, skid, mid):
    return _pydart2_api.marker__getBodyNode(wid, skid, mid)
marker__getBodyNode = _pydart2_api.marker__getBodyNode

def marker__getLocalPosition(wid, skid, mid):
    return _pydart2_api.marker__getLocalPosition(wid, skid, mid)
marker__getLocalPosition = _pydart2_api.marker__getLocalPosition

def marker__setLocalPosition(wid, skid, mid, inv3):
    return _pydart2_api.marker__setLocalPosition(wid, skid, mid, inv3)
marker__setLocalPosition = _pydart2_api.marker__setLocalPosition

def marker__getWorldPosition(wid, skid, mid):
    return _pydart2_api.marker__getWorldPosition(wid, skid, mid)
marker__getWorldPosition = _pydart2_api.marker__getWorldPosition

def marker__render(wid, skid, mid):
    return _pydart2_api.marker__render(wid, skid, mid)
marker__render = _pydart2_api.marker__render
# This file is compatible with both classic and new-style classes.


