
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "30070bf4ff000bc862c8231b7e1a96f34500cc7b",
 "version": "1.0.0.post.dev231"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
