
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.27.0'
version_full = '6ca78cecaaf2fe434e5efc0a2866776f1ba881b6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

