
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "206db01116688d17b73b1fd47cdd89e96ad01027",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
