heat_template_version: 2014-10-16
description: AutoScaling Infoblox DNS Service
parameters:
  mgmt_network:
    type: string
    description: the management network
  service_network:
    type: string
    description: the network for the DNS service
  external_network:
    type: string
    description: the network for the public floating IPs (with external GM)
    default: public
  min_members:
    type: number
    description: the minimum number of members to keep alive
    default: 2
  max_members:
    type: number
    description: the maximum number of members allowed in the stack
    default: 5
resources:
  nios_member_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: {get_param: min_members}
      max_size: {get_param: max_members}
      resource:
        type: autoscale-member.yaml
        properties:
          mgmt_network: {get_param: mgmt_network}
          lan1_network: {get_param: service_network}
          external_network: {get_param: external_network}
          parent_stack_id: {get_param: "OS::stack_id"}
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: nios_member_group}
      cooldown: 900
      scaling_adjustment: 1
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: nios_member_group}
      cooldown: 600
      scaling_adjustment: -1
  qps_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      description: If the avg QPS > 100 for 120 seconds then scale up
      meter_name: nios.dns.qps
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 100
      alarm_actions:
        - {get_attr: [scaleup_policy, alarm_url]}
      matching_metadata: {'metadata.metering.stack': {get_param: "OS::stack_id"}}
      comparison_operator: gt
  qps_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      description: If the avg QPS < 10 for 120 seconds then scale down
      meter_name: nios.dns.qps
      statistic: avg
      period: 120
      evaluation_periods: 1
      threshold: 10
      alarm_actions:
        - {get_attr: [scaledown_policy, alarm_url]}
      #matching_metadata: {'metadata.metering.stack': {get_param: "OS::stack_id"}}
      comparison_operator: lt

outputs:
  scale_up_url:
    description: >
      Invoke the scale-up operation by doing an HTTP POST to this
      URL;
    value: {get_attr: [scaleup_policy, alarm_url]}
  scale_dn_url:
    description: >
      Invoke the scale-down operation by doing an HTTP POST to
      this URL;
    value: {get_attr: [scaledown_policy, alarm_url]}

