heat_template_version: 2014-10-16
description: An Infoblox Grid Member
parameters:
  mgmt_network:
    type: string
    description: the network for MGMT
  lan1_network:
    type: string
    description: the network for LAN1
  external_network:
    type: string
    description: the external network for floating IP allocations
    default: public
resources:
  host_name:
    type: OS::Heat::RandomString
    properties:
      length: 12
      sequence: lowercase

# We pre-allocate the port for LAN1, so that we have the IP address already for
# injection via user_data
  lan1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: lan1_network }

# For MGMT, we do not configure via injection, but we do configure via WAPI
# at the time of member creation, so we want to pre-allocate that port too

  mgmt_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: mgmt_network }

# If the GM is outside the cloud, each member needs its own floating IP so that
# they are associated with separate NAT addresses.
# Even if the GM is in the cloud, you may need this if you want Ceilometer to
# poll the member for QPS, and you are not configuring the MGMT port
# Or if you want to actually do DNS from outside the cloud
#  lan1_floating_ip:
#    type: OS::Neutron::FloatingIP
#    properties:
#      floating_network: { get_param: external_network }
#      port_id: { get_resource: lan1_port }

# Since we want to access the UI and have Ceilometer poll, we need a fip for
# the mgmt port
  mgmt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: mgmt_port }

  grid_member:
    type: Infoblox::Grid::Member
    properties:
      name: { list_join: [ '.', [{ list_join: [ '-', [ 'nios', { get_resource: host_name } ]] }, 'localdomain' ]] }
      model: IB-VM-810
      MGMT: { get_resource: mgmt_port }
      LAN1: { get_resource: lan1_port }
      dns: { enable: True }
      licenses: ["vnios", "dns", "enterprise"]
# If you do not have a license pool and want to use temp licenses instead,
# uncomment the line below
      #temp_licenses: ["vnios", "dns", "enterprise"]
      gm_ip: 10.2.0.3
# To get your GM certificate you can use the following command:
#   echo | openssl s_client -connect gm_ip_address:443 2>/dev/null | openssl x509
#
      gm_certificate: -----BEGIN CERTIFICATE-----MIIDdzCCAl8CEEZ4MABmScxA8/It6d9u5dcwDQYJKoZIhvcNAQEFBQAwejELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExEjAQBgNVBAcTCVN1bm55dmFsZTERMA8GA1UEChMISW5mb2Jsb3gxFDASBgNVBAsTC0VuZ2luZWVyaW5nMRkwFwYDVQQDExB3d3cuaW5mb2Jsb3guY29tMB4XDTE1MTAwODE1MzIxMloXDTE2MTAwNzE1MzIxMlowejELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExEjAQBgNVBAcTCVN1bm55dmFsZTERMA8GA1UEChMISW5mb2Jsb3gxFDASBgNVBAsTC0VuZ2luZWVyaW5nMRkwFwYDVQQDExB3d3cuaW5mb2Jsb3guY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwFepWL9I2plWiepM7BFkjTn9ZZ9bir5vKcvTsu8IjvLJuoayEP92c/yR+ArWRPVGFEk49yCT4wzhQ1bQXI/oJ1XmoZaJZVXcwXFDKNaaZcc8UDusisZvyl3rPJbMgumsRQK8UTUAAvQFLPlQTAHDAq2ZPR8uU5zXtTgfq0EUDkY66jjbbxPbul7rpWRYkP9Z7b4HwG9okQGmEZt51Wn4d9nDNjXuUFXYxEuMm085ynOXZ015EPGpbzVtLs4PHfJeMel3pyYBXJI6VFbXbt7G/wh1GFAbKU9fGIQMR0DskP2r+9cTrtegwlDWpNpv/BwNdKHn2jMNomWJxqPMRlD1ywIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQC4u05QIe46gAUZNDNwmAbao1S6Br/P89IiaK9zwfmfB+cduQa3CIzRE2CMLC3gVNIcmx/1JvxpYhrUviqrtimy5Nst6eUt51fog4BFaM58TeKOs09bz3a+WCDPjDOAxSGMGEgYdOkhyDvTEiRtBdc+sdSM2HzNWFOfqCvb+sBk69dI3qUNubtO2cucDqzdayY8FSxS2aQp/lIRlm9Y19Y1AcHWWlsYcuKHixNPEeow4YLDeap1ZzIvqlZFgX5X72j9Wt4jNZxTqTeoqHbohz1bEq/v1JX76hIqT8xQ8MFCbGk8b1XRF+XrNuNqwKJt4SJQlkMmbZENsgqufw2afuOF-----END CERTIFICATE-----
# If your GM is outside the cloud, you must uncomment the line below so that
# the floating IP is configured in the GM for this member.
      #nat_ip: { get_attr: [ lan1_floating_ip, floating_ip_address ] }
      remote_console_enabled: true
      admin_password: infoblox

  grid_member_ns_group_entry:
    type: Infoblox::Grid::NameServerGroupMember
# Make sure it is created only after the member is created
    depends_on: grid_member
    properties:
# You need to define the group in the GM and list its name here.
      group_name: default
      member_role: grid_secondary
# The name: of the member_server must be the grid member name.
      member_server: { name: { list_join: [ '.', [{ list_join: [ '-', [ 'nios', { get_resource: host_name } ]] }, 'localdomain' ]] } }

  server:
    type: OS::Nova::Server
    properties:
      name: { get_attr: [grid_member, name] }
      flavor: vnios810.55
      image: nios-7.2.3-810-55.qcow2
      networks: [{port: {get_resource: mgmt_port} }, {port: { get_resource: lan1_port}} ]
      user_data_format: RAW
      user_data: { get_attr: [grid_member, user_data] }
      metadata: { nios: true }
outputs:
  member_service_address:
    value: { get_attr: [lan1_port, fixed_ips] }
  user_data:
    value: { get_attr: [grid_member, user_data] }
