language: python
python:
  - "2.7"
# HTSeq is not compatible with python3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
# command to install dependencies
install: "pip install ."
# command to run tests
script: "python setup.py test"

notifications:
  email: false
