
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8769d932aebf77c97bf2380ff17f96594023ca7f",
 "version": "0.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
