
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6a94c2e0b466fce13aabaa81112dc42f5c906372",
 "version": "1.0.0a12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
