# This file was auto-generated by salt's setup on Friday, 22 July 2016 @ 17:07:17 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 11, 0, 0, 0, None)
