
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "86b49e7acfe89d4cef70d140e2ed4c3fa81f7154",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
