# Prefer docker container with setuid/sudo
sudo: required

language: python

cache: pip

addons:
  postgresql: "9.4"

env:
  - TOXENV=py26-mysql
  - TOXENV=py27-mysql
  - TOXENV=py26-postgres
  - TOXENV=py27-postgres
  - TOXENV=py26-sqlite
  - TOXENV=py27-sqlite
  - TOXENV=py34-sqlite
  - TOXENV=py34-postgres
  - TOXENV=py34-mysqlclient
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-egenix-mxdatetime python-mysqldb python-psycopg2

install: pip install tox coveralls codecov

matrix:
  fast_finish: true

script: tox -e ${TOXENV}

after_success:
    - cd sqlobject
    - coveralls
    - codecov
