
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "cfff29b6a644ca3bbb63148fa6550005ce896b55",
 "version": "1.2.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
