
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "4b43cb882cdf7a38e4011a9b8d358840960d08e5",
 "version": "0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
