
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "af76a6710a6170973ad1b1dfa9a71f8f16d26f03",
 "version": "0.post.dev255"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
