
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "78f789e7f09ff3e931414b477a051d3d72c040a5",
 "version": "0.4.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
