heat_template_version: 2014-10-16
description: An Infoblox NetMRI Job
parameters:
#  device_id:
#    type: string
#    description: the NetMRI DeviceID
  device_ip:
    type: string
  network_view:
    type: string
  command:
    type: string
    description: the command to run
    default: "show ver"
resources:
  netmri_job:
    type: Infoblox::NetMRI::Job
    properties:
      connection: { host: netmri, api_version: 3, username: admin, password: per1sc0pe1, sslverify: False, use_ssl: False }
      source: { script: "Ad Hoc Command Batch" }
      #targets: [ { device_id: { get_param: device_id } } ]
      targets: [ { device_ip_address: { get_param: device_ip }, network_view: { get_param: network_view } } ]
      inputs: { commands_to_be_executed: { get_param: command } }
      wait: True
outputs:
  job:
    value: { get_attr: [netmri_job, job] }
  job_details:
    value: { get_attr: [netmri_job, job_details] }
