
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "22c729bc23eaec127624a944c82748fcd6b3831e",
 "version": "0.post.dev51"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
