
# This file was generated by 'versioneer.py' from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.4'
version_full = 'f8254ab42b853a1f7b422f43e0deec1968200eaf'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

