# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_oauth_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_reg_code',
            field=models.CharField(db_index=True, max_length=25),
        ),
    ]
