# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_oauth_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_scope',
            field=models.CharField(choices=[('READ_WRITE', 'Read Write'), ('READ_ONLY', 'Viewer')], default='READ_WRITE', max_length=255),
        ),
    ]
