# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160111_1810'),
        ('accounts', '0004_auto_20160108_1546'),
    ]

    operations = [
    ]
