# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_scope',
            field=models.CharField(choices=[('write', 'Read/Write'), ('read', 'Read Only')], default='write', max_length=255),
        ),
    ]
