# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160119_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_scope',
            field=models.CharField(choices=[('read write', 'Read/Write'), ('read', 'Read Only')], default='write', max_length=255),
        ),
    ]
