# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160427_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_scope',
            field=models.CharField(choices=[('read write', 'Read/Write'), ('read', 'Read Only')], default='read write', max_length=255),
        ),
    ]
