# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160503_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='utc_offset',
            field=models.SmallIntegerField(default=0),
        ),
    ]
