# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_utc_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='utc_offset',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
