# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160713_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='utc_offset',
            field=models.CharField(default='+00:00', max_length=10),
        ),
    ]
