# слэш в конце пути обязателен
basedir: /ss13srv/
port: 7777

# названия билдов в этом файли и в builds.txt должны совпадать
builds:
  - name: baystation12
    folder: infinity-bay
    repo: infinity-baystation

  - name: tgstation
    folder: infinity
    repo: infinity-tg
