
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5186ecca7fefa468af85aa2a18edf920a6a1b4ce",
 "version": "0.1.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
