
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.6'
version_full = '4fb4abaca1388537137912419496ea8366c513a1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

