
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ebc098406bb7593941223917a465818d18a413e0",
 "version": "0.post.dev267"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
