
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e811756101a06975923ced6981b83ab83d8959d5",
 "version": "1.0.0a11+2.ge811756"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
