__version__ = "0.0.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@git.infinidat.com:host-opensource/infi.dnssimple.git'
__git_head_hash__ = 'd7300bcf1c1c0fb60844b3860fcb7a428dc7b6a0'
__git_head_subject__ = 'Finished Release v0.0.4'
__git_head_message__ = '* develop:\n  TRIVIAL ddns add'
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-07-07 12:19:32'
