
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4e75c245a41a108fc67d7bea08e3ddfb214ed553",
 "version": "0.post.dev340"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
