
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonThriftLibrary(BuildFileAddress(FilesystemBuildFile(/Users/kwilson/dev/commons/src/thrift/com/twitter/service/BUILD), finagle-py-thrift))

from setuptools import setup

setup(**
{   'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'twitter.common thrift stubs for zipkin rpc tracing support in finagle',
    'install_requires': [],
    'license': 'Apache License, Version 2.0',
    'name': 'twitter.common.finagle-thrift',
    'namespace_packages': ['gen', 'gen.twitter', 'gen.twitter.finagle'],
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': [   '.',
                    'gen',
                    'gen.twitter',
                    'gen.twitter.finagle',
                    'gen.twitter.finagle.thrift'],
    'url': 'https://github.com/twitter/commons',
    'version': '0.3.7',
    'zip_safe': True}
)
