
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.1'
version_full = '43bc73d4ccea66b7cf4bcc411bffad93924e972a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

