# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kanal ad\u0131n\u0131 giriniz', max_length=60, verbose_name='isim')),
                ('api_key', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='a\xe7\u0131klama')),
                ('enable', models.BooleanField(default=True, verbose_name='aktif et')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
