schema;contract:
  type: seq
  sequence:
    - type: map
      mapping:
        "before":
          type: str
    - type: map
      mapping:
        "after":
          type: str
    - type: map
      mapping:
        "always":
          type: str
    - type: map
      mapping:
        "sequentially":
          type: str

schema;transition:
  type: map
  mapping:
    "target":
      type: str
    "event":
      type: str
    "guard":
      type: str
    "action":
      type: str
    "contract":
      include: contract

schema;state:
  type: map
  mapping:
    "name":
      type: str
      required: yes
    "initial":
      type: str
    "memory":
      type: str
    "on entry":
      type: str
    "on exit":
      type: str
    "type":
      type: str
      enum: [final, shallow history, deep history]
    "states":
      type: seq
      sequence:
        - include: state
    "parallel states":
      type: seq
      sequence:
        - include: state
    "transitions":
      type: seq
      sequence:
        - include: transition
    "contract":
      include: contract

type: map
mapping:
  "statechart":
    type: map
    required: yes
    mapping:
      "name":
        type: str
        required: yes
      "description":
        type: str
      "preamble":
        type: str
      "root state":
        type: map
        required: yes
        include: state
