__version__ = "0.1.0"

# Import tokenizers
from dummy_package.tokenizer.alphabetic_tokenizer import AlphabeticTokenizer
from dummy_package.tokenizer.alphanumeric_tokenizer import AlphanumericTokenizer
from dummy_package.tokenizer.delimiter_tokenizer import DelimiterTokenizer
from dummy_package.tokenizer.qgram_tokenizer import QgramTokenizer
from dummy_package.tokenizer.whitespace_tokenizer import WhitespaceTokenizer

# Import similarity measures
from dummy_package.similarity_measure.affine import Affine
from dummy_package.similarity_measure.cosine import Cosine
from dummy_package.similarity_measure.dice import Dice
from dummy_package.similarity_measure.hamming_distance import HammingDistance
from dummy_package.similarity_measure.jaccard import Jaccard
from dummy_package.similarity_measure.jaro import Jaro
from dummy_package.similarity_measure.jaro_winkler import JaroWinkler
from dummy_package.similarity_measure.levenshtein import Levenshtein
from dummy_package.similarity_measure.monge_elkan import MongeElkan
from dummy_package.similarity_measure.needleman_wunsch import NeedlemanWunsch
from dummy_package.similarity_measure.overlap_coefficient import OverlapCoefficient
from dummy_package.similarity_measure.smith_waterman import SmithWaterman
from dummy_package.similarity_measure.soft_tfidf import SoftTfIdf
from dummy_package.similarity_measure.tfidf import TfIdf

