


# =========================================== Sections for the users

# list of your input file
samples:
    file1: "%(file1)s"
    file2: "%(file2)s"


project: "%(project)s"


# if files are required for a pipeline and are within sequana or should
# be downloaded before the pipeline provide them in this section
# Note that sequana and url fields are followed by itemised files or links using
# the front dashes
requirements:
    sequana:
        - Coliphage_phiX174.fa
    url:


# =========================================== For testing only
# If True, only a subset of the reads (N) are used

fastq_sampling:
    do: no
    N: 100000

# =========================================== Sections related to external tools



# GATK is absent in conda because it is not a free software
# You must set the GATK bin path.
# gatk_bin: "java -jar /path/to/GenomeAnalysisTK.jar"
gatk_bin: GenomeAnalysisTK

# Bwa parameter for reference mapping
bwa_ref:
    reference: "%(reference)s"
    index:
        options: '-a is'
    mem:
        options: '-T 30'
        # -R option for GATK
        read_groups: '@RG\\tID:1\\tSM:1\\tPL:illumina'
        # -t option (number thread)
        threads: 2 

# snpEff parameter
#Results filter options:
#	-fi , -filterInterval: Only analyze changes that intersect with the intervals specified in this file (you may use this option many times)
#	-no-downstream: Do not show DOWNSTREAM changes
#	-no-intergenic: Do not show INTERGENIC changes
#	-no-intron: Do not show INTRON changes
#	-no-upstream: Do not show UPSTREAM changes
#	-no-utr: Do not show 5_PRIME_UTR or 3_PRIME_UTR changes
#	-no EffectType: Do not show 'EffectType'. This option can be used several times.
 
snpeff:
    do: yes
    reference:
    options: "-no-downstream -no-upstream"

# Software parameters

bedtools: 
    options: '-d'

freebayes:
    options: '--ploidy 1'

indel_realigner:
    do: yes
    options: ''

mark_duplicates:
    do: yes
    options: ''

report_mapping:
    do: yes
    circular: yes
    window_size: 1001
    high_threshold: 3
    low_threshold: -3

vcf_filter:
    QUAL: 1000
    FREQ: 0.7
    INFO:
        DP: '>= 10'

fastqc:
    options: "--nogroup"


bwa_phix:
    do: yes
    reference: Coliphage_phiX174.fa
    index:
        options: '-a is'
    mem:
        options: '-T 30'
        read_groups: '@RG\\tID:1\\tSM:1\\tPL:illumina'
        threads: 2 

#################################################################
# Quality trimming and adapter removal
#   - quality: 0 means no trimming, 30 means keep base with quality 
#       above 30
#   - m: 20 means discard trimmed reads that are shorter than 20.
#   - tool: only cutadapt supported for now
#   ref: http://cutadapt.readthedocs.io/
#################################################################
adapter_removal:
    do: yes
    tool: cutadapt
    fwd: "%(adapter_fwd)s"
    rev: "%(adapter_rev)s"
    m: 20   # cutoff
    mode: "g"   # g for 5' adapter, a for 3' and b for both 5'/3'
    quality: "%(quality_cutoff)s"
    kwargs: "-O 6 --trim-n"


########################################################### Kraken
# For taxonomy. Used in quality_taxon pipeline
kraken:
    do: yes
    database: "%(kraken)s"

