
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "08becb412df214777e1852652b0315f2e104a84f",
 "version": "1.0.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
