heat_template_version: 2016-04-08

description: >
  OpenStack Cinder Volume service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  CinderVolumeBase:
    type: ../cinder-volume.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Cinder Volume role.
    value:
      config_settings:
        map_merge:
          - get_attr: [CinderVolumeBase, role_data, config_settings]
          - cinder::volume::manage_service: false
            cinder::volume::enabled: false
      step_config:
        include ::tripleo::profile::pacemaker::cinder::volume
