heat_template_version: 2016-04-08

description: >
  OpenStack Cinder Scheduler service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  CinderSchedulerBase:
    type: ../cinder-scheduler.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Cinder Scheduler role.
    value:
      config_settings:
        map_merge:
          - get_attr: [CinderSchedulerBase, role_data, config_settings]
          - cinder::scheduler::manage_service: false
            cinder::scheduler::enabled: false
      step_config:
        include ::tripleo::profile::pacemaker::cinder::scheduler
