heat_template_version: 2016-04-08

description: >
  Openstack Heat CloudWatch API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  HeatApiCloudwatchBase:
    type: ../heat-api-cloudwatch.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Heat Cloudwatch API role.
    value:
      config_settings:
        map_merge:
           - get_attr: [HeatApiCloudwatchBase, role_data, config_settings]
           - heat::api_cloudwatch::manage_service: false
             heat::api_cloudwatch::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::heat::api_cloudwatch
