heat_template_version: 2016-04-08

description: >
  OpenStack Keystone service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  KeystoneServiceBase:
    type: ../keystone.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Keystone pacemaker role.
    value:
      config_settings:
        map_merge:
          - get_attr: [KeystoneServiceBase, role_data, config_settings]
          - keystone::manage_service: false
            keystone::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::keystone
