heat_template_version: 2016-04-08

description: >
  OpenStack Neutron ML2 Plugin with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronMl2Base:
    type: ../neutron-plugin-ml2.yaml

outputs:
  role_data:
    description: Role data for the Neutron ML2 plugin.
    value:
      config_settings:
        map_merge:
          - get_attr: [NeutronMl2Base, role_data, config_settings]
          - neutron::agents::ml2::ovs::enabled: false
            neutron::agents::ml2::ovs::manage_service: false
      step_config: |
        include ::tripleo::profile::pacemaker::neutron::plugins::ml2
