heat_template_version: 2016-04-08

description: >
  OpenStack Neutron OVS agent with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronOvsBase:
    type: ../neutron-ovs-agent.yaml

outputs:
  role_data:
    description: Role data for the Neutron OVS agent service.
    value:
      config_settings:
        get_attr: [NeutronOvsBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::pacemaker::neutron::ovs
