heat_template_version: 2016-04-08

description: >
  OpenStack Nova Conductor service with Pacemaker configured with Puppet.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaConductorBase:
    type: ../nova-conductor.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Conductor role.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaConductorBase, role_data, config_settings]
          - nova::conductor::manage_service: false
            nova::conductor::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::nova::conductor
