heat_template_version: 2016-04-08

description: >
  OpenStack Nova API service with Pacemaker configured with Puppet.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaApiBase:
    type: ../nova-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaApiBase, role_data, config_settings]
          - nova::api::manage_service: false
            nova::api::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::nova::api
