heat_template_version: 2016-04-08

description: >
  OpenStack Nova Scheduler service with Pacemaker configured with Puppet.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaSchedulerBase:
    type: ../nova-scheduler.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Scheduler role.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaSchedulerBase, role_data, config_settings]
          - nova::scheduler::manage_service: false
            nova::scheduler::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::nova::scheduler
