heat_template_version: 2016-04-08

description: >
  OpenStack Nova Consoleauth service with Pacemaker configured with Puppet.

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NovaConsoleauthBase:
    type: ../nova-consoleauth.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Nova Consoleauth role.
    value:
      config_settings:
        map_merge:
          - get_attr: [NovaConsoleauthBase, role_data, config_settings]
          - nova::consoleauth::manage_service: false
            nova::consoleauth::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::nova::consoleauth
