heat_template_version: 2016-04-08

description: >
  RabbitMQ service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  RabbitMQServiceBase:
    type: ../rabbitmq.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the RabbitMQ pacemaker role.
    value:
      config_settings:
        map_merge:
          - get_attr: [RabbitMQServiceBase, role_data, config_settings]
          - rabbitmq::service_manage: false
      step_config: |
        include ::tripleo::profile::pacemaker::rabbitmq
