heat_template_version: 2016-04-08

description: >
  OpenStack Sahara Engine service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  SaharaEngineBase:
    type: ../sahara-engine.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Sahara Engine role.
    value:
      config_settings:
        map_merge:
          - get_attr: [SaharaEngineBase, role_data, config_settings]
          - sahara::service::engine::manage_service: false
            sahara::service::engine::enabled: false
      # No puppet manifests since sahara-engine is included in
      # ::tripleo::profile::pacemaker::sahara which is maintained alongside of
      # pacemaker/sahara-api.yaml.
      step_config:
