heat_template_version: 2016-04-08

description: >
  OpenStack Sahara API service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  SaharaApiBase:
    type: ../sahara-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Sahara API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [SaharaApiBase, role_data, config_settings]
          - sahara::service::api::manage_service: false
            sahara::service::api::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::sahara
