
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3e6f4713544a6223c8849832c9b80554b24a84b1",
 "version": "1.0.0.post.dev131"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
