
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "df570448276baf6a18e440670fe616c84a3c5faa",
 "version": "0.post.dev351"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
