
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "51506b3f97034708f63b20a1391026384550915c",
 "version": "0.3.1rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
