
# This file is automatically generated by setup.py, So don't edit it. :)
VERSION_INFO = {
    'final': True,
    'version': '1.7.1',
    'branch_nick': '(no',
    'revision_id': '2b315681f6b4429b2cdb2aecc5e971a494370365',
    'revno': 4344
}
