
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "406a45b267a7c26c7e397679b5759681ff1d5007",
 "version": "0.post.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
