
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "6c989043e5cc36c2a6eafd5e9c87ea44914f8904",
 "version": "1.0.0.post.dev237"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
