language: python
python:
  - "2.7"
before_install:
  - "export NO_EVENTLET=1"
install:
  - pip install tox --use-mirrors
before_script:
  - mysql -e 'create database quark_functional_tests;'
script:
  - tox
sudo: false
