build: false
environment:

  global:
    python: "C:\\Python27-x64"

  EPD_AUTH:
    secure: 8xQi8VNnhx6CdGMEbDsSRCeRh94jQdq1LX9nab6LAWSFaT3cEm61dD3wVtUqn5QM

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + "C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin;" + $Env:path

install:
  # Just test to see if we have a reasonable Python.
  - ps: python -c "import sys; print(sys.executable)"

  # Install enstaller, needed so we can quickly install numpy.
  - ps: Start-FileDownload 'https://s3.amazonaws.com/enstaller-assets/enstaller/bootstrap.py'
  - python bootstrap.py
  - ECHO EPD_auth = '%EPD_AUTH%' > %HOMEPATH%\.enstaller4rc
  - enpkg numpy

  # Install pysph related dependencies.
  - pip install -r requirements.txt

  # Build pysph.
  - python setup.py develop

test_script:
  # Run the tests.
  - python -m nose.core -v -A slow --with-xunit --xunit-file=nosetests.xml
