# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='element',
            name='device',
        ),
        migrations.AddField(
            model_name='element',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel', verbose_name='Kanal adi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='default_value',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='max_length',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='name_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number')], default=1, max_length=200, verbose_name='Element tipi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Element adi'),
        ),
        migrations.AlterField(
            model_name='element',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
