# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20160822_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='default_value',
        ),
        migrations.RemoveField(
            model_name='element',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='element',
            name='size',
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(default=1, max_length=70, verbose_name='Element adi'),
            preserve_default=False,
        ),
    ]
