
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0d0f1185ac3307094fc5f82448c270e9a9bc10c5",
 "version": "0.post.dev304"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
