
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "716e93adb9d213cb4625adce7ad636e67950a443",
 "version": "1.0.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
