
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": true,
 "error": null,
 "full-revisionid": "e35451cf36e656d7b04d35c5faa3c4c1ef147e4e",
 "version": "0.post.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
