
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E3F2B9F79489B9638B2741EF948DF3C9'
    
_lr_action_items = {'PHRASE':([0,3,6,7,],[5,5,5,11,]),'COLON':([2,],[7,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,],[-1,-2,-5,-1,0,-6,-1,-9,-3,-4,-7,-8,]),'WORD':([0,3,6,7,],[2,2,2,10,]),'SPACE':([0,1,2,3,5,6,7,10,11,],[3,6,-5,3,-6,3,-9,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Term':([0,3,6,],[1,1,1,]),'Terms':([0,3,6,],[4,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Terms","S'",1,None,None,None),
  ('Terms -> <empty>','Terms',0,'p_terms_empty','__init__.py',54),
  ('Terms -> Term','Terms',1,'p_terms_single','__init__.py',60),
  ('Terms -> SPACE Terms','Terms',2,'p_terms_leading_space','__init__.py',67),
  ('Terms -> Term SPACE Terms','Terms',3,'p_terms_multiple','__init__.py',74),
  ('Term -> WORD','Term',1,'p_term_single','__init__.py',82),
  ('Term -> PHRASE','Term',1,'p_term_single','__init__.py',83),
  ('Term -> WORD COLON WORD','Term',3,'p_term_field','__init__.py',90),
  ('Term -> WORD COLON PHRASE','Term',3,'p_term_field','__init__.py',91),
  ('Term -> WORD COLON','Term',2,'p_term_incomplete_field','__init__.py',98),
]
