# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2016-03-04 01:54:33.554588
from __future__ import unicode_literals
import datetime

version = "1.1"
githash = "929f4eb9774e532f8bcdd18eff2361b5f2d08732"


major = 1
minor = 1
bugfix = 0

release = True
timestamp = datetime.datetime(2016, 3, 4, 1, 54, 33, 554588)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
