
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.0b2'
version_full = '393d1bcaa41f4cc6f16a677b198d15bc6c66ee56'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

